### ISSUE TITLE
The position of the labels changes when no virtual device is found

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1001]
**Preconditions**
None.

**Steps To Reproduce**
1. Go to Virtual device manager
2. Delete all the tokens or use the filters so no virtual device is found

**Expected behavior**
The position of the labels remains the same 

**Actual behavior**
The position of the labels changes when no virtual device is found.

**Screenshots**
![no virtual devices](https://user-images.githubusercontent.com/39920441/49048315-44733200-f1a8-11e8-9708-f6df769e0c50.png)
![with virtual devices](https://user-images.githubusercontent.com/39920441/49048316-44733200-f1a8-11e8-917b-078cda1a7f63.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-203

**Additional context**
None.

**Comment by AnkRaiza** [comment]
@dmarvp this is happening because we have a flex size on the columns if we go static sizes we risk having some columns with more than 1 row of text, should we go static on the column sizes?

**Comment by dmarvp** [comment]
@AnkRaiza @MKen-li I think we can leave it as it is

**Comment by MKen-li** [comment]
Closing ticket
