### ISSUE TITLE
Validation is not escaping special characters

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1014]
**Preconditions**
Have a virtual device token and be on the validation page.

**Steps To Reproduce**
1. Enter a script that has an ampersand "&". Eg.: what is rock & roll?
2. Click on Run

**Expected behavior**
Validation should work correctly.

**Actual behavior**
Virtual device only receives what is rock?

**Additional context**
The problem is that we are sending the script as it is, without escaping special characters first. The ampersand should be turned into %26 in this scenario.

**Comment by MKen-li** [comment]
QA complete
Build = dev-217
