### ISSUE TITLE
My account page not counting the virtual devices correctly

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1017]
**Preconditions**
Have more than one virtual device created in the virtual device manager.

**Steps To Reproduce**
1. Go to My account.
2. Look at the count of virtual devices label

**Expected behavior**
The number should correspond to the number of virtual devices created.

**Actual behavior**
If one virtual device has been created using the old way, it will say 1. That number does not change.

**Additional context**
We should count the number of virtual devices under the "virtualDevices" property of the user's object. If we can't find anything there, then we should look for the silentEchoToken to just count 1.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-213
