### ISSUE TITLE
"My account" page title is missing

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1018]
**Preconditions**
Be a user of the Dashboard.

**Steps To Reproduce**
1. Go to My account page.

**Expected behavior**
The page should have a title saying "My Account"

**Actual behavior**
No title.

**Screenshots**
Current screen:
<img width="1518" alt="image" src="https://user-images.githubusercontent.com/6411740/49234230-abb9fd80-f3c5-11e8-9e2e-bef5b99c9fc7.png">

Mockup:
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/6411740/49234256-b70d2900-f3c5-11e8-88f5-386e88cd3179.png">

Virtual Device Manager example:
<img width="1516" alt="image" src="https://user-images.githubusercontent.com/6411740/49234313-cf7d4380-f3c5-11e8-8306-c692536f7d01.png">

**Additional context**
Also, make sure that the title refreshes correctly when changing between "My Account", "Virtual Device Manager" and other pages.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-213
