### ISSUE TITLE
Disabling outage notification should remove last status

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#1026]
### Summary

As a user with outage notification and validation that is removing the outage notification
I want to get status only from validation
so that any last down status from outage doesn't affect me.

### Acceptance Criteria

1. GIVEN: I have outage notification and validation enabled and the last outage is down
WHEN: I disable outage notification
THEN: Status should be las validation status

### Additional Resources

This will include changes on the monitor to do the change but needs to be triggered from the settings in the dashboard.

**Comment by dmarvp** [comment]
No need to fix as we are discontinuing this piece.
