### ISSUE TITLE
Set an expiration date for virtual devices when creating them

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1029]
### Summary
Virtual devices created within a trial period of the Dashboard should have the same expiration date as when the trial of the user ends.

### Acceptance Criteria

1. GIVEN: I'm a user on the free trial of the Dashboard.
WHEN: I create a virtual device.
THEN: The virtual device is created with an expiration date equal to the Dashboard account expiration date.

### Additional Resources
This should be done after https://github.com/bespoken/virtual-device/issues/226

**Comment by jricaldi** [comment]
This is the parameter to send `exp_date` with EPOCH format.
if the source doesn't have expiration date we should not send the parameter.

**Comment by dmarvp** [comment]
Moving back to dev:
It works from the validation page but from the virtual device manager, its adding the epoch date number but not the "&exp_date=" parameter. 

<img width="984" alt="image" src="https://user-images.githubusercontent.com/6411740/50568190-8e59b580-0d1c-11e9-912d-64d928bd3114.png">

**Comment by dmarvp** [comment]
Verified in build dev-226.
