### ISSUE TITLE
Trial period can be manipulated by changing your time in the pc

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1039]
**Preconditions**
None

**Steps To Reproduce**
1. Log in to the system
2. Change your date 

**Expected behavior**
The date doesn't affect the trial period.

**Actual behavior**
The date affects the trial period 

**Screenshots**
none.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-215

**Additional context**
None.

**Comment by jricaldi** [comment]
@jperata  This looks a new endpoint to get user data, also the validation should be in the backend.

**Comment by MKen-li** [comment]
Moving back to dev,
not fixed

**Comment by MKen-li** [comment]
moving back to dev

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-222
