### ISSUE TITLE
The message in the plan selection is wrong

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1041]
**Preconditions**
None.

**Steps To Reproduce**
1. Open the plan selection by clicking on "Subscribe now" or "Subscribe" 

**Expected behavior**
"Ops" message is displayed

**Actual behavior**
The correct message is "Choose the plan that's right for you"

**Screenshots**
![oops](https://user-images.githubusercontent.com/39920441/49765430-7ef8c680-fca0-11e8-9408-f12122f4e754.png)

**Environment:**
 - OS: win 10
 - Browser Chrome
 - Version dev-215

**Additional context**
None.

**Comment by jricaldi** [comment]
@MKen-li Expected behavior and Actual behavior are inverted. This ticket should be an enhancement instead of a bug, the expected behavior wasn't part of the original ticket #995.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-216
