### ISSUE TITLE
[Hot fix] Yaml editor data disappear 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1058]
**Preconditions**
Have 2 sources created:
Source A = visual editor
Source B = YAML editor

**Steps To Reproduce**
1. Open Source B
2. Use the drop-down to change to source A
3. Change to source B back

**Expected behavior**
The page is displayed correctly

**Actual behavior**
Data from YAML editor disappear

**Screenshots**
none.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version prod-1.0.57

**Additional context**
The issue is not reproducible on Dev environment

**Comment by MKen-li** [comment]
Similar behavior can be seen if the user changes between 2 sources in the visual editor. Data from Source A y displayed in Source B when using the source drop-down

**Comment by dmarvp** [comment]
Moving back to the sprint backlog, more work should be done to refactor the component before addressing this issue.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-297
