### ISSUE TITLE
Rearrange how the state is set on Validation Page

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#1068]
### Summary

As a developer
I want validation state to be set correctly
so that we can fix some issues and made it robust for new changes.

### Acceptance Criteria

At the moment when using validation Page, there are elements on the state that linger from children components and don't are set correctly from the parent component.
When the component has it's source changed an action in redux needs to call the service correctly and then set the different elements via props to the children components.

### NOTES

@jricaldi have some ideas in mind on how to tweak the component correctly. Check with him on this.

**Comment by jperata** [comment]
For QA on this change, we need to do regression testing on the Validation Page, #1058, for example, should not be present without needing additional work.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-282
