### ISSUE TITLE
Yaml Validation giving false positives

### ISSUE THREAD

**Issue by AnkRaiza** [bespoken/dashboard#1070]
**Preconditions**
You are on the validation page yaml version and have a valid script to run with an intentional error on the last utterance
**Steps To Reproduce**
1. Click Run
2. See the results on the right panel

**Expected behavior**
The results should always show an error if such error exist

**Actual behavior**
The result will be ok (with an error at the end) sometimes and all green sometimes (no error at the end even tho there is an error)

**Comment by MKen-li** [comment]
moving back to dev

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-227
