### ISSUE TITLE
Dashboard Sign Up Survey

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1075]
### Summary

As a Dashboard admin
I want to get more data from our new users
so that I can better understand their needs

### Acceptance Criteria

1. GIVEN: I'm a new user that has just signed up to the Dashboard
WHEN: I verify my email
THEN: I see a new Screen (Screen 1)
- Title: Your Bespoken Profile - Get more from testing automation!
- Sub: It takes only 30 seconds!
- Name
- Company
- Job Title
    - Product Manager / Owner
    - Software Developer
    - QA Analyst / Manager
    - Dev Ops
    - Director / Management
    - Other __________________
- Continue button

2. GIVEN: I have filled all the info
WHEN: I click on the continue button
THEN: I see a new Screen (Screen 2)
- Title: Help us to better help you!
- Sub: Tell us a bit about what automation tools are most important to you
- Sliders: (from 1 - Not important to 5 - Very important)
    - Usability Testing
    - Unit Testing
    - End to End Testing
    - Monitoring
    - Proxy
    - Logs and Stats
- Sub: and a bit more about your product
- Checkboxes: Which platforms are you developing for?
    - Alexa
    - Google
    - Others __________________
- Radio button: Are your voice apps live?
    - Yes
    - No
- Open question (text area): What is your biggest pain point with testing for voice? 

3. GIVEN: I'm on screen 2
WHEN: I have filled all data, I click on the continue button
THEN: I'm taken to the Dashboard landing page.

4. GIVEN: I'm on screen 1 or 2
WHEN: I haven't filled all the questions on the current page
THEN: The continue button is disabled.

5. GIVEN: I'm a user of the Dashboard.
WHEN: I log in after having already gone through the signup process (I have filled the survey)
THEN:  I'm taken to the Dashboard landing page.

### Additional Resources: Please read the AC's correctly as these screens might be outdated.

Screen 1.
<img width="984" alt="image" src="https://user-images.githubusercontent.com/6411740/50774503-9b692e00-1261-11e9-9d16-c4aed2e6ec5d.png">

Screen 2
<img width="985" alt="image" src="https://user-images.githubusercontent.com/6411740/50774547-b50a7580-1261-11e9-91aa-db7c2b033aa8.png">

### NOTES
- Need to figure out if we should also include some kind of validation message when a required field has not been filled.
- I recommend controlling if the survey was filled with a field on the user's object. This way we can make older users go through this process too.

**Comment by dmarvp** [comment]
@jperata , @jricaldi we can decide if we want the results of the survey stored in firebase or not, but **they do** need to be stored in intercom.

**Comment by jricaldi** [comment]
[verify-bespoken-08-01.pdf](https://github.com/bespoken/dashboard/files/2861715/verify-bespoken-08-01.pdf)
[login-bespoken.pdf](https://github.com/bespoken/dashboard/files/2861716/login-bespoken.pdf)

**Comment by MKen-li** [comment]
Marked as blocked
waiting for https://github.com/bespoken/dashboard/issues/1175 and https://github.com/bespoken/dashboard/issues/1176

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-295
