### ISSUE TITLE
Verify email page redesign

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1076]
### Summary
Verify email page redesign to get in line with the new sign up process.

### Additional Resources
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/6411740/51756766-c9d36f80-208f-11e9-9ece-58f0cd15ece4.png">

### NOTES
Functionality will remain almost the same as it is now, but a new button should be added after the text. The button should say "Back to Login" and will take the user back to the Login screen when clicked.

Text should say:
> ### Please Verify Your Email
> Your account has been created. Please check your email to verify your registration.
>
> If you haven't received a verification email, check your junk folder or [click here](url) to have another one sent to your inbox.

**Comment by dmarvp** [comment]
@jricaldi A couple of notes on this one:
1. The unleash your superpowers text should appear aligned as in the image I posted. If it can't be done with html, you can use the version of the image that had the text included in it. 
2. Please use the same font and alignment as in the image posted (Raleway, regular, left aligned)
3. There are division lines before and after the text, include those as well. 
4. The bespoken logo location should be the same as in the login page.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-252
