### ISSUE TITLE
Login page design update

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1077]
### Summary
This is a design update aligned with the rest of the new signup process.

### Acceptance Criteria
Functionality should remain the same.

### Additional Resources
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/6411740/51773581-4b8dc200-20bd-11e9-9411-f2f3ceaa4922.png">

### NOTES
- Reutilize the right panel in the login page and move it to the right. 
- Turn it into a component if it isn't right now (it's going to be reutilized across more pages)

**Comment by MKen-li** [comment]
For Johns feedback change the word WATCH for SEE in the left blue panel

**Comment by MKen-li** [comment]
Marking as blocked, waiting for bug fixes

**Comment by MKen-li** [comment]
Mark as verified
Build = dev-250

**Comment by MKen-li** [comment]
Reopen ticket, the messages are not centered

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-252
