### ISSUE TITLE
Remove the "Integration" tab and Settings button.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1080]
### Summary
Remove the integration tab.

<img width="294" alt="image" src="https://user-images.githubusercontent.com/6411740/51143914-b9183380-181d-11e9-8754-7bb350b45903.png">

Also change the right side panel on the source page from "Did you know?..." to:

> ### Move up to the next testing level!
> 
> Learn how to:
> - Use our CLI to quick test while developing voice apps
> - Unit test the code of your Voice app
> - Create Virtual Devices 
> - Write and run powerful end to end tests
> - Monitor your live voice apps 24/7
>
>### [Take me to the docs!](https://read.bespoken.io)

And change the right side panel on the validation page from "Unleash the beast..." to:

> ### Grow your Testing Superpowers!
> 
> Learn how to:
> - Create Virtual Devices
> - Write and run powerful end to end tests that support
>     - Transcripts
>     - Card objects
>     - Regular expressions
>     - JSONPath queries and much more!
>
>### [Take me to the docs](https://read.bespoken.io/end-to-end/guide)

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-235 
Some changes were made to the right panel after JPK input
