### ISSUE TITLE
Make the "Virtual Devices" option a new tab. 

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1081]
### Summary
Move the Virtual Devices option from the menu to a tab.

### Acceptance Criteria

1. GIVEN: I'm a user on Dashboard.
WHEN: I click on the three dots menu.
THEN: I do not see the Virtual Devices option.

2. GIVEN: I'm a user on Dashboard.
WHEN: I first enter Dashboard.
THEN: I see a tab called Virtual Devices, next to the validation tab.

2. GIVEN: I'm a user on Dashboard.
WHEN: I click on the Virtual Devices tab.
THEN: I see the Virtual Device Manager page.
    - **Important:** The page does not show the source dropdown at the tab level, since it's not tied to a single source.
    - The functionality remains the same, just the title "Virtual Device Manager" should now be in the content section and not at the top like it was before, since it's now inside of a tab.

### Additional Resources
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/6411740/51144803-21681480-1820-11e9-830e-3539c905d18c.png">

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-238
