### ISSUE TITLE
Update Webpack configuration

### ISSUE THREAD

**Issue by jricaldi** [bespoken/dashboard#1086]
### Webpack big changes

This ticket should take the following points:

- use the last version of Webpack
- enable Hot Module Replacement for ts, tsx, scss files
- deploy dist folder intead harness
- the dist folder should have bundle files from sass, ts/tsx(hashes to avoid cache issue)
- load correctly images(jpeg, png, gif) and svg files
- create different icons for all devices
- for development, use source-maps(scss, ts, tsx) to go directly to the file.

**Comment by MKen-li** [comment]
Moving back to dev
1. On Login Page Email and Password are not centered
2. Virtual devices aren't displayed
3. My account, Read the docs, etc options are too small
4. On the validation page, the virtual device label and dropdown are misaligned
5. When running a test in YAML or visual editor when loading the run button shows "img-status" with a broken image
6. The YAML and Visual editor the error or OK icon are not centered
7. The enable and toggle and tooltip are misaligned
8. In the visual editor, the Actual response is bigger than the input and expected
9. The text displayed in the tooltip is crushed
10. When deleting a source the buttons are to close to the text
11. The dismiss button in the snack bar is bigger than the snack bar
12. On the visual editor a broken image is displayed in the Actual before changing to the X

**Comment by MKen-li** [comment]
Marked as verified.
Build = dev-262
