### ISSUE TITLE
Use the secure "link_account" endpoint

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1088]
### Summary
The virtual device link_account endpoint has been secured. Send the correct JWT token and secret to be able to use it from Dashboard.

### Acceptance Criteria

1. GIVEN: I'm a user on the validation or virtual device manager page.
WHEN: I create a new virtual device.
THEN: Everything works as normal, new virtual devices are created.

2. GIVEN: I'm a user with the link_account url
WHEN: I try to access that url from any web browser and not from Dashboard
THEN: I get a 401 Unauthorized Request response.

### Additional context
Refer to: https://github.com/bespoken/virtual-device/issues/209

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-253
