### ISSUE TITLE
Trial end page update

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1089]
### Summary
1. Update the trial end page with the llama and clock graphic.
2. When on this page, hide the "My account" option from the menu.

### Additional Resources
<img width="379" alt="image" src="https://user-images.githubusercontent.com/6411740/51354237-fb8d7a80-1a80-11e9-8bec-d1a71eef469b.png">

### NOTES
Functionality will remain the same as it is now.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-250
