### ISSUE TITLE
No message is provided when using an expired token in Yaml editor

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1098]
**Preconditions**
Have an expired token

**Steps To Reproduce**
1. Go to YAML
2. Run a script with the token from the precondition

**Expected behavior**
The system shows the message "The trial period for your virtual device has expired. Please visit https://bespoken.io/testing/ to learn about our pricing or send us an email at support@bespoken.io to request an extension of your trial period."

**Actual behavior**
Nothing happens.

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-238 and prod

**Additional context**

**Comment by AnkRaiza** [comment]
bloqued on the visual editor part with https://github.com/bespoken/virtual-device-sdk/issues/108

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-266
