### ISSUE TITLE
Enable virtual devices on paid plans

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1103]
**Preconditions**
Be a user on a paid plan.

**Steps To Reproduce**
1. Go to Virtual Devices Manager or Validation Page
2. Create a new virtual device

**Expected behavior**
The virtual device is enabled as long as the user is subscribed to a plan.

**Actual behavior**
The virtual device is created in "trial" mode is deactivated after 30 days.

**Comment by MKen-li** [comment]
Marked as verified
Build = staging-58
