### ISSUE TITLE
New user's status field

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1109]
**Summary**
We need to update a new status property for users in Dashboard, and update current ones.

**Acceptance Criteria**
1. WHEN: A new user registers to the Dashboard.
THEN: 
- His status is set to __trial__
- A trialEndDate property is created (instead of calculating it every time as we do now)

2. WHEN: A user subscribes to a plan
THEN: 
- His status is set to __enabled__
- The user's virtual devices are updated to the enabled status (call the virtual device endpoint for doing that)

__ALSO__: Using the current logic we have, we need to run a script to update current users to the enabled and trial status (with trialEndDate).

**Additional context**
Unsubscribed and disabled status are being handled in other stories.
Trial date handling should be updated to use the trialEndDate property. This will give us flexibility to increase a users trial period if we so desire.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-266

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-266
