### ISSUE TITLE
Remove virtual devices limitation via benefits

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1112]
**Summary**
As an enterprise user I want to be able to create an unlimited amount of virtual devices.

**Acceptance criteria**

1. GIVEN: I'm a user whose benefits include a determined number of virtual devices.
WHEN: I go to the Virtual Devices Manager
THEN: I can create a maximum number of virtual devices depending on my benefits.

2. GIVEN: I'm a user whose benefits include an __unlimited__ number of virtual devices.
WHEN: I go to the Virtual Devices Manager
THEN: 
- I don't see the label saying "X/Y virtual devices"
- I can create as many virtual devices as I want.

**Additional context**
I think the best way to handle this is by using the benefits property of a user. We can either set it to "0" for infinite or to an string constant if we want to be more specific like "unlimited".

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-254
