### ISSUE TITLE
When loading the page, the page is zoom around 500% for a second

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1113]
**Preconditions**
None.

**Steps To Reproduce**
1. Go to Login Page

**Expected behavior**
The page loads correctly without showing any weird behavior

**Actual behavior**
The page shows for a few seconds the right side zoom

**Screenshots**
![zoom login](https://user-images.githubusercontent.com/39920441/51773283-598f1300-20bc-11e9-8bd1-cfe2e713926b.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome and FF
 - Version dev-245

**Additional context**

**Comment by dmarvp** [comment]
@jricaldi Why can't it work in dev as well? we have no way to test it otherwise.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-248
