### ISSUE TITLE
Restrict access to virtual devices creation by platform

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1116]
### Summary

As a user that has subscribed to a plan by platform
I want to be able to create virtual devices of the platform I have subscribed to.

### Acceptance Criteria

1. GIVEN: I'm a user that has subscribed to a single platform plan and I'm on the Virtual Device Manager page
WHEN: I click on Add a new virtual device
THEN: Only the platform I'm subscribed to is enabled to create a new virtual device. The other one should appear as disabled.

2. GIVEN: I'm a user that has subscribed to a cross-platform plan and I'm on the Virtual Device Manager page
WHEN: I click on Add a new virtual device
THEN: Both platforms are enabled to create a new virtual device. 

3. GIVEN:  I'm a user that has subscribed to a single platform plan and I'm on the validation page
WHEN: I click on monitoring for a platform that I'm not subscribed to.
THEN: I get the following message (snackbar):
    > Your current plan is "Single Platform - **platform**" If you want to enable monitoring for **current platform**, subscribe to a cross-platform plan.

### NOTES
We need to implement the new plans and benefits, but we can start work on this one if we:
- Add a platforms property (array) to the plan's benefits [google, alexa]
- Load the benefits of a plan into the user when logging in
- Merge those benefits with the benefits property on the user itself (where the user's benefits will overwrite the benefits of the plan if needed)

**Comment by MKen-li** [comment]
Marked as blocked waiting for story https://github.com/bespoken/technical-debt/issues/7

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-286
