### ISSUE TITLE
Disable virtual devices when deleting an account

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1141]
**Preconditions**
Be a user on the dashboard that has virtual devices created.

**Steps To Reproduce**
1. Go to My account.
2. Click on Delete my account and continue the process.

**Expected behavior**
Virtual devices for the user that has been deleted should be disabled.

**Actual behavior**
Users can still use their virtual devices as they are left untouched.

**Additional context**
Call the virtual device endpoint with DELETE to leave those virtual devices unusable.

**Comment by MKen-li** [comment]
Marked as verified
