### ISSUE TITLE
Double login is requested if you try to login with Github with the same email as you did with amazon

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1143]
**Preconditions**
None.

**Steps To Reproduce**
1. Go to Login Page
2. Login with Amazon 
3. Log out
4. Login with Github using the same email

**Expected behavior**
Github login is displayed an after entering the credentials the user can log in successfully

**Actual behavior**
Github login is displayed an after entering the credentials the Amazon login is displayed.

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-262 and prod-1.0.60

**Additional context**
None.

**Comment by jricaldi** [comment]
@MKen-li this happens because we need to link between different providers. you can do the same using gmail and github. you will see something like this in firebase:

![image](https://user-images.githubusercontent.com/2177405/52432525-a3262780-2ad8-11e9-9c86-4575ab4268a7.png)

**Comment by dmarvp** [comment]
@MKen-li @jricaldi the desired functionality is the following:
- If a user is trying to log in with a second (new) provider:
    - A message in red should appear saying: 
    > You have previously authenticated using a(n) [Amazon/Github/Google/Email and Password] account. Please, use the same method when logging in. 
- For users that have already linked multiple providers, we should let them keep their current providers but not add new ones.

**Comment by jricaldi** [comment]
@dmarvp ok, this is a new behavior I will change the ticket type, it should be an enhancement not a bug.

**Comment by MKen-li** [comment]
Moving ticket back to dev, currently, we have different responses of how we handle the authentication process:
Scenarios
1. Login with Amazon then Gmail X
2. Login with Amazon then Github (You have previously authenticated using a Amazon account. Please, use the same method when logging in.)
3. Login with Amazon then User pass (You have previously authenticated using a Amazon account. Please, use the same method when logging in.)
4. Login with Gmail then Amazon X
5. Login with Gmail then Git (You have previously authenticated using a Gmail account. Please, use the same method when logging in.)
6. Login with Gmail then User pass (You have previously authenticated using a Gmail account. Please, use the same method when logging in.)
7. Login with Git then Amazon X
8. Login with Git then Gmail X
9. Login with Git then User pass (You have previously authenticated using a Github account. Please, use the same method when logging in.)
10. Login with User pass then Amazon X
11. Login with User pass then Gmail X
12. Login with User pass then Git (You have previously authenticated using an Email and Password account. Please, use the same method when logging in.)

Also, change the message so it says "an Amazon account"

**Comment by jricaldi** [comment]
returning to "linking" behavior

**Comment by MKen-li** [comment]
Marked as verified
Build -297
