### ISSUE TITLE
Solution for using Bespoken with Persistance

### ISSUE THREAD

**Issue by rohitand** [bespoken/dashboard#1147]
### Summary
After adding this method .. .withTableName(skillSessionTable) skill stopped working using local Bespoken proxy. On searching the errors it seems when this function is invoked locally it is unable to find the region value since it's not invoked using Lambda....

{ AskSdk.DynamoDbPersistenceAdapter Error: Could not create table (SS_session): Missing region in config

How can we provide this region value hard coded in code for local testing?

**Comment by jkelvie** [comment]
Hi @rohitand this is a very common issue that comes up. To resolve it, you need to configure the region for the AWS API programmatically, as shown here:
https://stackoverflow.com/questions/43501436/dynamo-error-configerror-missing-region-in-config-when-developing-alexa-skill/43501437?noredirect=1#comment95947262_43501437

This code should be called before the ASK SDK handler is setup.

**Comment by jkelvie** [comment]
Here is an example of how it is done:
https://github.com/jkelvie/alexa-sample-college-finder-nodejs/blob/master/lambda/custom/index.js#L86

**Comment by rohitand** [comment]
Thank you, this works.
