### ISSUE TITLE
Migrate from Typings to @types

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#116]
TypeScript 2 is out and so is @types, we should move to using it.

 https://blogs.msdn.microsoft.com/typescript/2016/06/15/the-future-of-declaration-files/

**Comment by DeaVea** [comment]
Has this been fully released?

As of writing, fetch-mock, node, react-ga, react-global, and redux-mock-store are not in their database.

**Comment by michaelmyers** [comment]
It looks like it is now the recommended way to get the typings by DefinetlyTyped: https://github.com/DefinitelyTyped/DefinitelyTyped#how-do-i-get-them

Fetch-mock: https://www.npmjs.com/package/@types/fetch-mock 
Node: https://www.npmjs.com/package/@types/node
react-ga: https://www.npmjs.com/package/@types/react-ga 
react-global: couldn't find, not sure
react-mock-store: https://www.npmjs.com/package/@types/redux-mock-store

The way I understand how it works, the (at)types user just creates npm projects from the DefinatelyTyped typings that are in that repo.  

I did try this briefly, it didn't seem as straight forward as it should be.

**Comment by DeaVea** [comment]
React-global seems to be a way of injecting global variables in to a desktop app.  We don't import it in packages.json, but we have the typings for it which is why I looked it up.

**Comment by DeaVea** [comment]
And the reason for the question was because the site I found had a search engine where you could search the packages.  For whatever reason they didn't exist on that site.

**Comment by michaelmyers** [comment]
Closing for now.
