### ISSUE TITLE
"Subscription" section on My account update for utterances quotas

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1163]
### Summary

As a user of the Dashboard
I want to be able to quickly see how much of my monthly quota I have used so far
so that I can adjust my usage if necessary

### Acceptance Criteria

1. GIVEN: I'm a user subscribed to a plan in Dashboard.
WHEN: I go into "My account" page.
THEN: I see the following under the subscription section.
    - Current Plan:
        - Either "Cross Platform" or "Single Platform - Alexa" / "Single Platform - Google" depending on the user's subscription. The value for single platform can be taken from the user's benefits.
    - Utterances Usage: X/Y
        - X is the current number of utterances used **since my last billing date.**
        - Y is the utterances quota assigned to my plan.
    - Virtual devices, Monitored voice apps and Logs captured this month have been reordered. If there are no limits on the plan or for the user, the "/Y" part won't appear.

2. GIVEN: My utterances usage is less than 60% of my quota.
WHEN: I look at the "X/Y" label for utterances.
THEN: The "X" part has a green font.

3. GIVEN: My utterances usage is equal or greater than 60%  and less than 90% of my quota.
WHEN: I look at the "X/Y" label for utterances.
THEN: The "X" part has a yellow font.

4. GIVEN: My utterances usage is equal or greater than 90%  and less than 100% of my quota.
WHEN: I look at the "X/Y" label for utterances.
THEN: The "X" part has an orange font.

5. GIVEN: My utterances usage is equal or greater than 100%  of my quota.
WHEN: I look at the "X/Y" label for utterances.
THEN: The "X" part has a bold red font.

6. GIVEN: I don't have any integrated source.
WHEN: I look at the subscription section.
THEN: I won't see the "Logs captured this month" label

### Additional Resources
<img width="336" alt="image" src="https://user-images.githubusercontent.com/6411740/52517336-0bbff200-2c08-11e9-9002-3f08dd394d01.png">

### NOTES
Data for the number of utterances is stored as virtual device stats. To get it, we'll have to match the user's virtual devices to the ones in stats.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-291
