### ISSUE TITLE
Generate CSS bundles on production

### ISSUE THREAD

**Issue by jricaldi** [bespoken/dashboard#1167]
Currently, we are doing a lot of requests to get each style from each component.

![image](https://user-images.githubusercontent.com/2177405/52622218-3fed1a00-2e77-11e9-9fdf-bf95d391576b.png)

To avoid this behavior we need to build a CSS optimized bundles using the mini-css-extract-plugin for webpack 4.

**Comment by MKen-li** [comment]
Marked as verified
Build = staging-68
