### ISSUE TITLE
Logical deletion of virtual devices

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1172]
**Preconditions**
Have at least one virtual device created.

**Steps To Reproduce**
1. Go to virtual device manager
2. Delete the virtual device

**Expected behavior**
1. The virtual device status is set to: disabled on firebase and dynamo.
2. The virtual device does not appear anymore across the Dashboard. Check:
    - Virtual Device manager
    - Validation Dropdowns
    - Count of virtual devices in My account.

**Actual behavior**
1. The virtual device is set to: disabled in dynamo.
2. The virtual device does not appear anymore.

**Additional context**
When querying the virtual devices please list any virtual device that is not on **status=disabled.** As there will be one more status besides "enabled" and "disabled".

**Comment by MKen-li** [comment]
Moving back to dev.
AC #2 not correctly implemented

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-301
