### ISSUE TITLE
Survey functional issues

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1176]
**Preconditions**
None.

**Steps To Reproduce**
1. Log in with a new user

**Bugs**
1. The "apps live?" radio button doesn't have a default value
2. The slider option should be set by default in the "important/middle" option 
3. There is no "Subscribe to our newsletter" button.
4. All text values should be set to a maximum of 255 characters.

**Environment:**
 - OS: Win 10 
 - Browser Chrome
 - Version dev-274

**Additional context**
None.

**Comment by jricaldi** [comment]
Product Owner decisions:

- there is no default value for app Live
- the default value was No Important (we never discuss this)
- the "subscribe to our newsletter" is part of a different ticket.
- there are no maximum characters( we never discuss this )

@MKen-li Are you already discuss those points with @dmarvp?
I need confirmation from PO to convert this ticket into an enhancement.

**Comment by MKen-li** [comment]
After talking to @dmarvp the only points that you need to change are 1 and 4. Also changing the ticket to enhancement

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-294
