### ISSUE TITLE
Single sign-on for usability testing

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#1177]
### Summary

As a usability performance tester
I want to have secure access to my usability testing account
so that I can view my reports easily and be certain others cannot view them

### Acceptance Criteria

1. GIVEN: I'm a new or existing Bespoken user
WHEN: I try to go to https://usability.bespoken.io, on a browser where I am not already signed in
THEN: I am redirected to a login/registration workflow.
The login workflow will borrow from the Dashboard.
The user will go through the same signup process, and at the end will be redirected back to the usability page.

**Technical aspects**
The process will be initiated when the Usability site redirects to:
https://apps.bespoken.io/dashboard?redirectURL=<URL_TO_REDIRECT_BACK_TO>

The normal login workflow will occur. If the user is new, they can create a new account. If the user is existing, they will just login.

At the conclusion, a Firebase verify ID token will be retrieved within the Dashboard React app, using the approach outlined here:
https://firebase.google.com/docs/auth/admin/verify-id-tokens

The code that needs to be included looks like this:
```
firebase.auth().currentUser.getIdToken(/* forceRefresh */ true).then(function(idToken) {
  // redirect to redirectURL here
}).catch(function(error) {
  // Handle error
});
```

The user will then be redirected back to the URL provided in the initial redirect, with the additional query string appended as `token=<VERIFY_ID_TOKEN>`.

The usability site will then use the token to authenticate and authorize the user, using the Firebase Admin SDK.

# Additional considerations
Why this approach?

1. It is important that our customer data be secured - so we need some sort of authentication process
2. We do not want to build a new authentication process - it is time-consuming and difficult, and the one we have for the dashboard works great.
3. We cannot easily merge the usability piece into the existing dashboard

We may choose over time to merge the dashboard and usability piece, but that is still to be decided. In the meantime, we need to accomplish goals 1 and 2.

**Comment by jkelvie** [comment]
@AnkRaiza @dmarvp Please take a look at this issue when you have a chance. I'd appreciate your feedback on it.

**Comment by AnkRaiza** [comment]
👍 i do think this is a good approach, plus i see on the documentation that the idToken created by the sdk already uses JWT so we are good just using it directly on the query string as detailed @dmarvp i think i can start working on this as a ticket, just let me know

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-321
