### ISSUE TITLE
Suspended virtual devices on Dashboard

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1195]
### Summary

As a user that has changed from a Cross-Platform plan to a Single platform one
I want to be able to still see virtual devices that are not on my plan even if I can not use them.

### Acceptance Criteria

1. GIVEN: I'm a user that has virtual devices with status = suspended.
WHEN: I'm on the virtual device manager 
THEN:  
    - I see a new column called Status. 
    - The new column goes after the virtual device name.
    - The new column shows the status of the virtual device.
    - The refresh button is disabled for virtual devices with status=suspended.

2. GIVEN: I'm a user that has virtual devices with status = suspended.
WHEN: I'm on the validation page and one of the suspended virtual devices is selected.
THEN:
    - The refresh button is disabled for virtual devices with status=suspended.

### Additional Resources
<img width="832" alt="image" src="https://user-images.githubusercontent.com/6411740/53127683-15632700-3531-11e9-8731-13cb6b622060.png">

**Comment by MKen-li** [comment]
Moving back to dev.
1. When a user changes from cross-platform to single platform the virtual devices of the unselected plan changes to suspended and are reflected in the status column.
2. The refresh button is disabled for virtual devices that are suspended (virtual device manager and validation page)

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-301
