### ISSUE TITLE
My account: "Change my plan"

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1206]
### Summary

As a user **subscribed** to a plan in Dashboard.
I want to be able to change my plan

### Acceptance Criteria

1. GIVEN: I'm a **subscribed** user of the Dashboard (Single or Cross-Platform plans)
WHEN: I go into "My account page"
THEN: I see the following under the Subscription section
- An information icon. Tooltip: More info. Link: https://bespoken.io/blog/bespoken-pricing-plans/
- My current plan name (including Alexa or Google if the user is on a single platform plan)
- A "Change" link next to the current plan name

2. GIVEN: I'm a **subscribed** user of the Dashboard on My account page.
WHEN: I click on the "Change" link next to my subscribed plan name.
THEN: The payment modal shows up.
- If I'm on a Cross-Platform plan, the Cross-Platform option should be disabled.

3. GIVEN: I'm a **subscribed** user of the Dashboard with a **Cross-Platform" plan on the payment modal.
WHEN: I select a single platform.
THEN: Both platforms are enabled to select.

4. GIVEN: I'm a **subscribed** user of the Dashboard with a **Single Platform** plan on the payment modal.
WHEN: I select a single platform.
THEN: Only the platform I'm not on is enabled to select.

### Additional Resources
<img width="326" alt="image" src="https://user-images.githubusercontent.com/6411740/53344897-bb23e680-38e1-11e9-875a-cc6ab369353f.png">

### NOTES
The change link is only for subscribed users. Not users on trial. Also not Enterprise users.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-317
