### ISSUE TITLE
Intercom: User plan is not being updated.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1207]
**Preconditions**
Change a user plan.

**Steps To Reproduce**
1. Login into the Dashboard.

**Expected behavior**
Information should be sent to Intercom and updated.

**Actual behavior**
The user plan remains the same.

**Additional context**
We are probably updating the user's plan after going through the payment flow. That is fine, but we also need to update the user's data on each login. Especially since some of the users are updated manually.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-299
