### ISSUE TITLE
Intercom: Send user's current status, subscribedPlatforms as a new tags. Remove duplicated tags.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1208]
### Summary
The user's status should be part of the tags on Intercom.

### Acceptance Criteria
1. GIVEN: I'm a user of the Dashboard.
WHEN: I try to log in.
THEN: Tags are updated in Intercom. 
- A new tag is included **"userStatus"**, coming from the users own "status" field. The values are slightly modified in name for clarity. 
Possible values:
    * onTrial -> corresponds to our "trial" status.
    * trialEnded -> user has the "trial" status and the trialEndDate has passed.
    * subscribed ->corresponds to our "enabled" status.
    * unsubscribed -> corresponds to our "unsubscribed" status.
    * disabled -> corresponds to our "disabled" status.
- Another new tag is **"subscribedPlatforms"**. 
Possible values:
    * google
    * alexa
    * alexa, google
- Another new tag is **"trialEndDate"**. 
    - It must be sent as a Unix Timestamp.

2. GIVEN: I'm a user of the Dashboard.
WHEN: I subscribe to a plan.
THEN: The userStatus in Intercom is updated with "subscribed".
The subscribedPlatforms is updated accordingly.

3. GIVEN: I'm a subscribed user of the Dashboard.
WHEN: I unsubscribe from a plan.
THEN: The userStatus in Intercom is updated with "unsubscribed".

### NOTES
- There's a duplicate tag: skillsAmount and numSources. Please **remove skillsAmount** from the tags that are sent to Intercom.
- For AC1, Intercom tags should be updated even if the login presents the user with a Verify Email, Trial Ended or Renew Subscription page.
- AC2 and AC3 should update tags on those actions instantly. Without the user needing to log in again for it to be reflected.

**Comment by dmarvp** [comment]
@jricaldi: I Added a new field to intercom: "trialEndDate" to AC2
**NOTE:** the date must be sent in a Unix Timestamp.

**Comment by MKen-li** [comment]
Marked as block waiting for:
https://github.com/bespoken/dashboard/issues/1250
https://github.com/bespoken/dashboard/issues/1249
https://github.com/bespoken/dashboard/issues/1248

**Comment by MKen-li** [comment]
Marked as verified
Build  = dev-318
