### ISSUE TITLE
Add a loading screen after login in

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1228]
### Acceptance Criteria

1. GIVEN: I'm a user of the Dashboard
WHEN: I click the Log In button
THEN: I see the loading icon and overlay while I wait for the Dashboard to load.

### NOTES
Take a look at the validation page and save a script there to see how the loading overlay works.

**Comment by MKen-li** [comment]
Moving back to dev.
Loading icon is not displayed for Amazon, Gmail, and GitHub users.

**Comment by MKen-li** [comment]
Marked as verified
Builid = dev-323
