### ISSUE TITLE
Survey: Tab order not working correctly on Job Title.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1229]
**Preconditions**
Be a user on the survey page.

**Steps To Reproduce**
1. Go to the dashboard survey.
2. Click on the Job title.
3. Tab through the options.

**Expected behavior**
The tabs take me one by one through the options.

**Actual behavior**
The tabs go from the first option to the last directly.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-306
