### ISSUE TITLE
Ability to Filter by Intent

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#123]
In the /logs view, it would be helpful to filter down by a specific intent.

The filter list would need to be populated based on what is currently available in the list.

**Comment by chrsdietz** [comment]
I have the "Filter by Intent" added, but I noticed it does not correspond by the name here:

![screen shot 2017-01-27 at 9 52 11 am](https://cloud.githubusercontent.com/assets/16545947/22374994/5d7a2984-e476-11e6-8368-daee084676cc.png)

If I type "Open", then it filters appropriately.  If I type "IntentRequest", it does not. This seems rather confusing.  The "IntentRequest" seems to be hard coded and not actually part of the conversation.

**Comment by michaelmyers** [comment]
What is shown on the list item is `requestPayloadType`.  For intents, the request payload type is just `IntentRequest`.  I found it to be more helpful for display and when calculating the total number of different types of requests to append the intent to the end of `IntentRequest` making it `IntentRequest.Open` (see this [line](https://github.com/bespoken/dashboard/blob/master/src/models/conversation.ts#L128)).  

The filter is working correctly.  What we might want to address is maybe showing the intent type in a different manner on the list?  Would that clear up the confusion?

**Comment by chrsdietz** [comment]
Yes.  I think it would.  At first I kept tying "Intent" to see if it worked, but it kept clearing the list. I didn't realize that "Send" and "Open" were the intents.

**Comment by michaelmyers** [comment]
Appending the Intent to the request payload probably isn't a good idea either, might be better to instead create a new derived field.
