### ISSUE TITLE
UI: Vertically center the trial ended and renew subscription pages

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1231]
**Preconditions**
Be on the trial ended or renew subscription pages in Dashboard.

**Expected behavior**
1. The message is shown at the middle of the screen vertically.

2. On the renew subscription page, the llama should appear at least 30% smaller and centered. (it seems left aligned right now)

**Actual behavior**
The message is next to the header with no spacing at all.

**Screenshots**

<img width="1505" alt="image" src="https://user-images.githubusercontent.com/6411740/53652493-05290700-3c17-11e9-97bc-285181ae190d.png">

![image](https://user-images.githubusercontent.com/6411740/53652519-1540e680-3c17-11e9-9285-722e4cc57b70.png)

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-309
