### ISSUE TITLE
My account: Include Job Title

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1235]
### Summary

As a user of the Dashboard
I want to be able to update my job title on my account page

### Acceptance Criteria

1. GIVEN: I'm a user of the Dashboard
WHEN: I go into "My account"
THEN: 
- I can see an option to input my Job Title under Company.
- The options correspond to the ones shown on the Dashboard Survey including the "Others" option
- Data must be saved each time a radio button is clicked or when the text field for others is left (copy the approach for the Name and Company fields.

### Additional Resources

<img width="334" alt="image" src="https://user-images.githubusercontent.com/6411740/53743057-ff763000-3e67-11e9-99cf-32d9de53375e.png">

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-323
