### ISSUE TITLE
The trialEndDate changes to Unknown when unsubscribing

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1249]
**Preconditions**
Have a user subscribe  to any plan

**Steps To Reproduce**
1. Log in with the user of the precondition
2. Go to my account page
3. Click the unsubscribe button
4. Go to intercom and look at the trialEndDate

**Expected behavior**
The value remains as it was before

**Actual behavior**
The value changes to unknown

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-311

**Additional context**

**Comment by jricaldi** [comment]
@dmarvp @MKen-li  his happens because when we subscribe to a plan we remove the "trialEndDate" field from firebase.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-317
