### ISSUE TITLE
The "Crash" and the "Debug" titles are different fonts

### ISSUE THREAD

**Issue by chrsdietz** [bespoken/dashboard#126]
It seems weird.

<img width="692" alt="screen shot 2016-12-21 at 5 51 03 pm" src="https://cloud.githubusercontent.com/assets/16545947/21409034/203710c4-c7a6-11e6-838b-5e213c3e4d57.png">

**Comment by michaelmyers** [comment]
I agree, whoever implemented this got a little lazy.  As discussed, I think just showing the top most stack trace element and then hiding the rest of the stack (which can be opened) would be a good solution.
