### ISSUE TITLE
"trialEnded" status on Dashboard

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#1276]
### Summary
Until now, we've been handling when a user sees the "Trial ended" page by looking at the status = "trial" and trialEndate <= today. With this ticket, we'll introduce another status for that "trialEnded". 

### Preconditions
Have a user whose trial days are over.

### Acceptance Criteria
1. GIVEN: I'm a user whose trial days are over.
    - status = trial, trialEndDate <= today
    - status = trialEnded

WHEN: I try to log in to the Dashboard.

THEN: 
  - I'm presented with the trial ended page.
  - We won't change the user status on this ticket (that's going to be done by our daily job)
  - The userStatus in intercom for "trialEnded" should not be calculated here.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-330
