### ISSUE TITLE
userStatus and PlanId are not being saved when the users is registered using gmail or amazon

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#1277]
**Preconditions**
None.

**Steps To Reproduce**
1. Register a new user using Amazon or Gmail
2. Check on intercom the information the values for userStatus and PlanId

**Expected behavior**
The information is saved correctly

**Actual behavior**
Fields are shown as unknown

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version prod-1.0.63

**Additional context**

**Comment by jperata** [comment]
We need to update the affected users, all should be in a trial with a crossPlatform plan. It seems like the trialEndDate is not being saved neither, so we would need to generate their trialEndDate based on the creation date from their authentication data

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-328
