### ISSUE TITLE
Slow Skill Summary Page Load Time for Skill that has been Selected Previously

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#140]
### Expected Behavior
For a source with a bunch of data, click the source from the '/' root home page and the summary pages loads immediately however without the data.

### Actual Behavior

There is about a five second delay where the UI appears frozen before actually going to the summary page. 

### Reproduction Steps

1. Load a skill with a lot of data
2. Load another skill 
3. Go back to the root skills list
4. Load the skill you loaded in step one.

**Comment by chrsdietz** [comment]
This seems to have gotten fixed in this commit.  https://github.com/bespoken/dashboard/commit/943e565aa86bdb78ba547ed9682074014d554acd

**Comment by michaelmyers** [comment]
Agreed, I can no longer replicate with provided reproduction steps.    :shipit:
