### ISSUE TITLE
Allow Start Date in Previous month

### ISSUE THREAD

**Issue by pathigbie** [bespoken/dashboard#154]
The Start Date needs to allow the user to select a previous month/year.  
![screen shot 2017-01-03 at 12 06 11 pm](https://cloud.githubusercontent.com/assets/6854934/21615852/3d8f98ce-d1ad-11e6-86fa-37e86ae1b6c9.png)

**Comment by michaelmyers** [comment]
This will be fixed when #149 is merged and deployed (dev version available here: https://build-dashboard-57502.firebaseapp.com)

![screen shot 2017-01-03 at 12 31 33 pm](https://cloud.githubusercontent.com/assets/921356/21616730/b34329d4-d1b0-11e6-80d4-bbaa83988779.png)

**Comment by michaelmyers** [comment]
Confirmed fixed in #149
