### ISSUE TITLE
Add ability to link to log

### ISSUE THREAD

**Issue by chrsdietz** [bespoken/dashboard#163]
As of right now, you can link directly to a logs page like so:

`{host}/dashboard/skills/{sourceid}/logs`

It would be nice to look directly at a selected page via URL with parameters.  Like:

`{host}/dashboard/skills/{sourceid}/logs&id={convoId}`

This would allow collaborators to exchange the URL and go directly to it.

**Comment by michaelmyers** [comment]
It would be nice if we also included the startTime and endTime so a specific search can be shared.

`{host}/dashboard/skills/{sourceid}/logs&id={convoId}&startTime={startTime}&endTime={endTime}`

We could also add if there is a log type filter active or crash only filter active.

**Comment by jkelvie** [comment]
Based on discussion this morning, we need to add:
1) A logless-server API query that allows for filtering to a particular conversation ID
The query should allow for specifying the number of logs to grab before and after the conversation.
For example, if surrounding_logs is set to 25, it will grab 25 logs before and after the specified conversation ID.

2) Only one conversation ID can be specified
There should be no multiple selection allowed on mobile.
Separately, and this is tracked as its own issue #276, when the user selects a transaction on mobile, they should be taken to a detailed view of the transaction.
