### ISSUE TITLE
When today's date is selected as starting date, then no data displays

### ISSUE THREAD

**Issue by pathigbie** [bespoken/dashboard#170]
![screen shot 2017-01-07 at 5 31 34 pm](https://cloud.githubusercontent.com/assets/6854934/21745705/499b35ce-d4ff-11e6-8315-9cb28b16f191.png)
### Expected Behavior
When today's date is selected as starting date, then no data displays
### Actual Behavior
When today's date is selected as starting date, data displays
### Reproduction Steps

**Comment by michaelmyers** [comment]
I can no longer reproduce, looks to have been fixed in #177.  Closing.
