### ISSUE TITLE
Add tail function for logs

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#184]
When looking at the logs for a particular skill, it should allow for auto-refresh.

This can be an option, such as adding a "LIVE" or "TAIL" toggle at the top.

With it, it should automatically add the latest logs at the top of the screen. Ideally, it should feel as close to live as possible.

**Comment by michaelmyers** [comment]
I'm thinking we want to trigger this two ways: 
1.  An auto-refresh every 5 seconds, this only happens when a "TAIL" option is checked in the filterbar.
2. A "pull-to-refresh" pattern where the user scrolls to the top and it queries for the latest.

**Comment by michaelmyers** [comment]
We don't want the entire page refreshing, we just want the new logs/conversations added at the top.  We will eventually want to animate them in, probably with a CSS class.
