### ISSUE TITLE
Request Not Being Populated for Certain Logs

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#205]
### Expected Behavior

All logs (assuming the data is good) should display the request and response. 

### Actual Behavior

Left Side is current production, right side is the Dev Site with the same log

<img width="1431" alt="screen shot 2017-02-01 at 3 24 36 pm" src="https://cloud.githubusercontent.com/assets/921356/22524948/45afa556-e893-11e6-997c-ba9b9c5b8a22.png">

### Reproduction Steps

Not sure what is causing it exactly.

**Comment by michaelmyers** [comment]
We determined this was caused by conversations with several console statements that would not fill up enough of the list so it didn't scroll.  Since it didn't have enough conversations to be scrolled, it did trigger the auto-load on scroll.

**Comment by chrsdietz** [comment]
Fixed in #229
