### ISSUE TITLE
Dates are not uniform

### ISSUE THREAD

**Issue by chrsdietz** [bespoken/dashboard#208]
The dates on the summary page are not uniform when there are not items for every hour of the day.

![screen shot 2017-02-02 at 4 20 11 pm](https://cloud.githubusercontent.com/assets/16545947/22570266/a8eae628-e968-11e6-83c5-880be8732eeb.png)

There should be gaps or "0" in place of these.

**Comment by michaelmyers** [comment]
Fixed in #209
