### ISSUE TITLE
With Live Update Enabled, Only Make Request if the Document Has Focus

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#219]
In order to cut down on CPU usage and network calls while a LogExplorer tab is simply open but not in use, check [Document.hasFocus()](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus) before making the call.  We also might want to suspend the update executor whenever the page has lost focus.  The [Visibility API](https://developer.mozilla.org/en-US/docs/Web/API/Page_Visibility_API) has a `visibilitychanged` event that can be listened to for this information.

**Comment by chrsdietz** [comment]
I'm pretty sure this is already implemented. The tail is turned off when the component unmounts. Doing some testing, it unmounts every time you switch tabs.

**Comment by chrsdietz** [comment]
Oh wait.  You meant tabs on the browser.
