### ISSUE TITLE
Support Page

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#23]
Provide a page at `/dashboard/support` to show users how they can get help, report bugs, or request features.

**Comment by michaelmyers** [comment]
Report a Bug Link: https://github.com/bespoken/dashboard/issues/new?labels=bug 
Feature Request Link:  https://github.com/bespoken/dashboard/issues/new?labels=feature%20request&body=

Support/Contact Email: contact@bespoken.tools

**Comment by michaelmyers** [comment]
We also want this link available on every page somewhere.

**Comment by chrsdietz** [comment]
Being that it's only three links would it need to be on every page? Most websites put this kind of stuff on a footer like so:

![footer example](https://www.dropbox.com/s/zc2lw03lo27fnnp/Screen%20Shot%202016-11-02%20at%206.16.05%20PM.png?dl=1)

Our Dashboard does not have this.  It seems more apt to put it in the About page for now.
