### ISSUE TITLE
Add Google Action Timeseries Event Data to Existing Alexa Data

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#232]
<img width="1405" alt="screen shot 2017-02-22 at 6 06 31 pm" src="https://cloud.githubusercontent.com/assets/921356/23237174/2c48e80a-f92a-11e6-963b-92f5b57d7bbf.png">
(Please excuse the extremely bad photoshop)

We want to display the Google Action data along side the Alexa data in the current time series events graph.

**Comment by chrsdietz** [comment]
It turns out that the graph actually contains both already.  (All events contain all logs).  Should this be separated out or contained in one?  The IntentCounts and Unique Users are not accurate though.
