### ISSUE TITLE
Add Spokes Configuration to Settings Page

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#236]
The configuration for a user's spoke setup will live on the source's settings page.

<img width="541" alt="screen shot 2017-03-01 at 7 46 13 am" src="https://cloud.githubusercontent.com/assets/921356/23460396/313d7e6a-fe53-11e6-8862-d0956d34c5d1.png">

**Comment by chrsdietz** [comment]
I think this has been added unless I'm mistaken

**Comment by michaelmyers** [comment]
This is dependent on the settings page existing, #235.  The information is on the integration page, which may make this ticket/feature redundant.
