### ISSUE TITLE
Create a new Source from URL

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#237]
For fast & easy Source creation & onboarding, we want the ability to create a new source from the supplied query parameters in a URL.  

The URL would be of some format like:

```
https://bespoken.tools/dashboard?id=mighty-goose&code=<HASHED_KEY> 
```

To workflow needs to be as follows:

1.  If the user does not exist or is not logged in, the user will first be directed to the login/signup page, then directed to the dashboard
2. The dashboard receives the query parameters, determines if the skill exists for the user, if it doesn't it is created automatically.
3. The dashboard redirects you to the logs page of the skill.

**Comment by chrsdietz** [comment]
What would be the "Name" of the source in this case? The ID is a slugified version of the name.

**Comment by chrsdietz** [comment]
Also, if the id or secret key exists but the user does not have access to it, it would have to generate a new one.  Is this acceptable?  I think the user would be confused of this outcome.

**Comment by chrsdietz** [comment]
Is the point of this to create a new source or link to link a source from the Spokes CLI interface?  In which case, it should error out if the source ID does not exist with the secret key.

**Comment by michaelmyers** [comment]
> What would be the "Name" of the source in this case? The ID is a slugified version of the name.

Good question.  How about just set it to the ID and they can update it later if they like?  I would assume trying to convert the ID back to a name would have too many edge cases to actually work.  Lets make the ability to change the name a ticket for later once we get the [Settings page in](https://github.com/bespoken/dashboard/issues/235). 

> Also, if the id or secret key exists but the user does not have access to it, it would have to generate a new one. Is this acceptable? I think the user would be confused of this outcome.

I think I would see this manifesting in two ways:

1.  The user creates a source from the CLI.  This source is not yet in the DB and is not associated with the user.  They have not clicked through on the URL that would create this source and associate it with the user.  Someone else creates another source from the CLI that gets the same ID (low probability but possible).  They click through before the original user and they get the ID.  If the first user then tries to click through, they will get an error that they don't have access.  
2. Something happens and for some reason the CLI spits out a URL with a source the user does not have access to.  

If we do create a new ID once we recognize this error, I agree, it would confuse the user.  I would also expect there then to be a discrepancy between what the CLI thinks the ID and key are.  It is probably best to just let the user know they don't have access with a 404.

> Is the point of this to create a new source or link to a source from the Spokes CLI interface? In which case, it should error out if the source ID does not exist with the secret key.
 
To also answer the previous question and try to address this one, what if the name generator creates the source at the time of the request but leaves it in a detached state, it is reserved but does not have a user?  This would prevent collisions and at some point in the future, if we pass some type of user credential with the name generation request we could automatically associate it with the user.   However, these leaves us open to the possibility that if somebody gets access to your ID and secret key, they could claim it and then get your data.

**Comment by chrsdietz** [comment]
So some updates since this is last posted.  There are now two remote services that can create sources and link them to users.  The CLI can then be responsible for for creating the source through this remote service.  When the user then clicks through the URL, it will be up to the dashboard to "link" them to the user.
