### ISSUE TITLE
Monitor ping service

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#284]
The monitoring service should intermittently ping the specified endpoint (either HTTP or Lambda) with a simple GET request to see that it is alive. In the case of a Lambda, it should send an empty JSON payload.

It should ping the service every five minutes by default, which will have side benefit of keeping Lambdas "warm". Read this article for more info on cold-starts and Lambdas:
https://serverless.com/blog/keep-your-lambdas-warm/

The monitor should record the results of each ping in a dynamo table, along with the response time taken by the service. The results should include the HTTP status code, and if the status code is not 200, the payload (so that we can potentially show the error to the user).

The monitor should send a simple GET request. Future versions will support more complex payloads.

**Comment by jkelvie** [comment]
In creating this as a micro-service, I would suggest using Hyper.sh and Circle CI for CI, CD and hosting. You can look at the spokes project for an example:
https://github.com/bespoken/spokes/blob/master/circle.yml

**Comment by jkelvie** [comment]
We will use the Spokes to monitor Lambdas. The Spoke URL is returned per this change: 
https://github.com/bespoken/source-name-generator/issues/12

**Comment by chris-ramon** [comment]
closing this one, addressed via monitor service.
