### ISSUE TITLE
once logged out user should not be allowed to get back to the home page or log page by pressing the back arrow

### ISSUE THREAD

**Issue by neupanekeshav** [bespoken/dashboard#29]
When logged out, user should not be allowed to get back to the page by pressing (browser's)back button. 
Logged out : 
![image](https://cloud.githubusercontent.com/assets/11166738/19566821/a0a24670-96b9-11e6-9590-fe5942436190.png)

Pressed the <-- and user is back in 

![image](https://cloud.githubusercontent.com/assets/11166738/19566856/bb45e518-96b9-11e6-84c1-aa07645c9d0e.png)

Also when a user is logged in multiple tabs, when logged out from one tab, another opened tab session should also be logged out if tried to navigate within the dashboard.

**Comment by chrsdietz** [comment]
I believe this is fixed now.

**Comment by neupanekeshav** [comment]
This is now fixed.
