### ISSUE TITLE
Evaluate Dashboard kits

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#297]
Take a look at various dashboard options that are available. We want to evaluate them for their functionality, visual design, and technical design.

Some useful resources:
https://dashing.io
http://www.cssauthor.com/dashboard-frameworks/
http://play.grafana.org/dashboard/db/grafana-play-home?orgId=1
http://www.cyclotron.io/
http://keen.github.io/dashboards/
http://www.astronomer.io/blog/six-open-source-dashboards

Please prepare an initial analysis on three or so frameworks you think are interesting. Include criteria for evaluation and scores for each. Example of this sort of analysis:
https://docs.google.com/a/bespoken.tools/spreadsheets/d/1vWrIrswrEOPhWom69SjnRwrPlaKUIgLEVGZNAqaAWhg/edit?usp=sharing

Once we have discussed the initial analysis, we will then choose one to do a prototype with.

**Comment by AnkRaiza** [comment]
After some evaluation to some of the kits offered out there (see https://drive.google.com/open?id=1y2yYw5_z65XulOPJnWfHjrMB_w43VYX6ev7gilU7BOA) we decided as a team to go for an in house inplementation, i'm going to commit some ui improvements (responsive design and some changes to the current charts) and link those to this ticket.
