### ISSUE TITLE
Change terminology from Skills to Sources

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#299]
On the welcome page when a user first signs up, it should read:
"You don't have any data sources yet, create one here."

When the user selects to add a source it should say:
"New Source Setup"

and

"Currently all data sources must be at least three characters in length and not contain any special characters."

and the button should read:
"Create Source"

If there are other places that say Skill, please mention them in a comment and we can discuss how to handle.

**Comment by AnkRaiza** [comment]
i think we should definitely change:

Enter the name of your skill and then click Create Skill.

Then, to start sending logs, follow the instructions on how to integrate the SDK into your skill.
