### ISSUE TITLE
Source sorting is out of order

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#342]
### Expected Behavior
Sources in the source list should be sorted by name, case-insensitive

### Actual Behavior
It appears that the source list is being sorted by id rather than name, as newer sources where the name and id are not the same show up in seemingly random places in the list.

See the output below - "A Test Skill to Delete" is a new one that I added:
<img width="703" alt="screen shot 2017-05-29 at 3 07 51 pm" src="https://cloud.githubusercontent.com/assets/17267/26561028/b0ce1d42-4480-11e7-9e3b-cf39d73d5758.png">

### Reproduction Steps
Add sources, see that their names are out of order

**Comment by chris-ramon** [comment]
Should it be sorted by created date?, because users might want to see latest skills created first in the list.

**Comment by jkelvie** [comment]
I think anything other than alphabetical is likely to confuse.

-John

**Comment by jkelvie** [comment]
#344
