### ISSUE TITLE
Send users to new silent echo registration endpoint

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#430]
The new endpoint for getting tokens for the silentecho is:
https://virtual-device.bespoken.io/link_account

With query string:
user_id: The dashboard user id to link
redirect_url: The URL to send the user back to once completed

The redirect_url should be the validation page that the user started on.

**Comment by chris-ramon** [comment]
closing this one, already landed to master and deployed to prod, via: https://github.com/bespoken/dashboard/pull/411#issuecomment-328153416
