### ISSUE TITLE
Cannot save skill settings

### ISSUE THREAD

**Issue by onedotover** [bespoken/dashboard#431]
### Expected Behavior
Going to skill settings and changing the name should let me save.

### Actual Behavior
The save button is not activated so I can't save.

### Reproduction Steps
Go to skill settings page and change any setting. Save is always disabled.

**Comment by jkelvie** [comment]
The fix will be deployed out shortly for this:
https://github.com/bespoken/dashboard/pull/432/

To workaround in the meantime, you can add a value to the URL field (the screen requires it even when monitoring is not enabled, which is a bug).
