### ISSUE TITLE
Use SMAPI integration to validate user is owner of skill

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#464]
We can use the Skill Management API to verify which skills a user is associated with, and limit them to invoking skills which they are the owner of:
https://developer.amazon.com/docs/smapi/ask-cli-intro.html#smapi-intro

To implement this, we need to add:
1) Add additional scopes to token authorization process
For getting the token on the validation page, we want to add the scope:
alexa::ask:skills:read
alexa::ask:models:read

The user will be granted a token that has this additional privilege.

For users that have older tokens, they will get an error message when they run the new validation page that they need to refresh their token.

2) Scrape the SMAPI to get the skills the user manages
This should be done inside the source-api, when it gets the new token from the silent echo service.

The data from the calls should be captured in the Firebase DB and associated with the user.

Each skill associated with the user should be stored as a "skills" record, with the following fields:
id - Skill ID
interactionModel - The full interaction model
skillManifest - The skill manifest
userID - The user ID that imported this skill (a skill may still be associated with multiple users)

Additionally, the user record on users should contain a "skills" array that contains an array of skill IDs associated with the user.

3) Add an endpoint to source-api to check if a token has access to a particular skill
/skill_authorized
The endpoint will take an invocation name, and will return plain text with either:
AUTHORIZED
NOT_AUTHORIZED
UNKNOWN

In the case of unknown, it means the user has not granted the correct privileges to access the skill. They should be shown a message saying: "Security token lacks sufficient information. Please re-authenticate with Amazon here to update your security token."

4) The silent echo sdk should call the new /skill_authorized endpoint with the invocation name of the skill before running each sequence. If it is not authorized, a message should be shown to the user.

**Comment by jkelvie** [comment]
We will also need to capture the vendor ID for the user on the validation page - this is a required parameter to make the list skills call. The vendor ID for a user can be found here:
https://developer.amazon.com/mycid.html

We should add a field for this, as well as instructions for how to retrieve it.

The field should go above the token, and say below it:
To retrieve your vendor ID, [click here](https://developer.amazon.com/mycid.html). Please make sure it is for the correct organization if you belong to multiple.

**Comment by jkelvie** [comment]
From initial review:

1) The vendor ID and token take up too much space on the page - can we make these sections smaller by:
A) Reducing font size? 
B) Reducing spacing between the fields and the text below them
Overall, these fields should consume much less screen real estate

2) The link to get the vendor ID should open a new tab/page.

3) The vendor ID should be saved if the user clicks the get token link
If the user enters a vendor ID, then hits get token, the vendor ID disappears

4) When running against a skill, it did not seem to validate using my skills
I was able to use both we study billionaries (which I own, but in a different org than my vendor ID) and cat facts (which I do not not own).
What happened? I am testing against the build-dashboard-57502 instance.

**Comment by chris-ramon** [comment]
> The vendor ID and token take up too much space on the page - can we make these sections smaller by:
> A) Reducing font size?
> B) Reducing spacing between the fields and the text below them
> Overall, these fields should consume much less screen real estate
> 

![vp-after](https://user-images.githubusercontent.com/1000404/32241431-14283a3a-be3e-11e7-8222-439bbeb60686.png)

> The link to get the vendor ID should open a new tab/page.
> 
good call!, addressed on: https://github.com/bespoken/dashboard/pull/466/commits/dc9c176af898802fd5046daeaa116bb725bc45e1

> The vendor ID should be saved if the user clicks the get token link
> If the user enters a vendor ID, then hits get token, the vendor ID disappears
> 

![output](https://user-images.githubusercontent.com/1000404/32246155-144e6cb0-be4c-11e7-9fd9-847c10cb38b6.gif)

> When running against a skill, it did not seem to validate using my skills
> I was able to use both we study billionaries (which I own, but in a different org than my vendor ID) and cat facts (which I do not not own).
> What happened? I am testing against the build-dashboard-57502 instance.

Testing should be against bbcee instance.
