### ISSUE TITLE
Small enhancements to Validation

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#477]
A few small enhancements to the page:
1) The initial example shows just "open we study billionaires": "welcome"
Instead, it should show a sequence:
```
"open guess the price": "how many persons are playing today"
"two": "tell us what is your name"
"john": "tell us what is your name"
"pier": "guess the price"
"100 dollars": "*"
```

2) Change "click here for help" - "click here to expand instructions"

3) For the error message on invalid token for skill, provide more info.
It currently says:
```
Security token lacks sufficient privileges to invoke "Uber Skill"
```

```
Security token lacks sufficient privileges to invoke "Uber Skill".

To correct this, make sure in the [Alexa developer console](LINK) that the skill is associated with your account.

If you are still having issues, contact us [support@bespoken.io](LINK).
```

**Comment by jkelvie** [comment]
Also, one question - it seems that the SMAPI integration pulls in more than just the skills associated with the vendor ID - is that right? We study billionaires, for example, which is associated with the XAPPmedia vendor ID (not Bespoken) is pulled in.

**Comment by chris-ramon** [comment]
> Also, one question - it seems that the SMAPI integration pulls in more than just the skills associated with the vendor ID - is that right? We study billionaires, for example, which is associated with the XAPPmedia vendor ID (not Bespoken) is pulled in.

- That's correct, at the moment, it pulls more skills than the ones related to the given vendor ID.
- Using user's access token, we obtain all vendor IDs that user has access as either administrator or developer role, endpoint: [`https://developer.amazon.com/docs/smapi/vendor-operations.html#get-vendor-list`](https://developer.amazon.com/docs/smapi/vendor-operations.html#get-vendor-list).
- For each vendor ID obtained, we retrieve all skills related to it, endpoint: [`https://developer.amazon.com/docs/smapi/skill-operations.html#list-skills`](https://developer.amazon.com/docs/smapi/skill-operations.html#list-skills).

**Comment by jkelvie** [comment]
Okay, very helpful
