### ISSUE TITLE
Logs Page and When to Request New Logs

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#51]
The LogsPage has some weird logic about when it requests logs, there is probably a better way of doing this.

**Comment by chrsdietz** [comment]
Is this still relevant?  I forget what this was about.

**Comment by michaelmyers** [comment]
We did not love the logic [here](https://github.com/bespoken/dashboard/blob/master/src/pages/LogsPage.tsx#L103).  

My current feeling is that it isn't very elegant how we search through the sources to find one that matches the current path.  The ticket is to see if there is a better way, that logic does not seem like it should be on the LogsPage, the source should be known before it gets there.  

It might be better handled in an onEnter method in the index.tsx for anything within the `/skills/sourceId` routes.
