### ISSUE TITLE
login with amazon (UI Changes)

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#519]
- [x] Add a "Login with Amazon" button above the "Login with Github" button on Dashboard login. Should not do anything for now, backend changes will be handled on #518 .

**Comment by dmarvp** [comment]
estimated time: 0.5 days

**Comment by robertonotte** [comment]
@dmarvp It doesn't seem to open the pop-up windown. 
Behaviour: 
Went to https://dev-dashboard-bbcee.firebaseapp.com/
Clicked: Login with Amazon.
Video: https://drive.google.com/open?id=19qZTpBxwBKEFaF0CrMA7usHYenzskang

**Comment by dmarvp** [comment]
@robertonotte this ticket only handles adding the button, the button functionality is going to be handled in #518 .

**Comment by dmarvp** [comment]
To test it:

- With an amazon user:
1. Go to: https://dev-dashboard-bbcee.firebaseapp.com/dashboard/login
2. Click on login with amazon button
3. Enter your amazon credentials
4. Verify that the new amazon landing page appears

![loginwithamazon](https://user-images.githubusercontent.com/6411740/35125197-b52857d2-fc76-11e7-83dd-29fa2899263f.gif)

- Without an amazon user:
1. Go to: https://dev-dashboard-bbcee.firebaseapp.com/dashboard/login
2. Enter your credentials and Click on login OR login with github
3. Verify that the previous landing page appears

![normallogin](https://user-images.githubusercontent.com/6411740/35125296-1c007dc2-fc77-11e7-9e04-55f82d0cfd64.gif)

**Comment by dmarvp** [comment]
@robertonotte No need to refresh the page. Logging in with amazon takes a bit more than a direct login because there is not a direct integration between firebase and amazon, so we have to internally go through source-api first to actually log in, just wait a couple of seconds without refreshing the page. Just tried this on chrome:

![login w amazon](https://user-images.githubusercontent.com/6411740/35235889-705e11e6-ff73-11e7-8919-26eabc135e8f.gif)

**Comment by dmarvp** [comment]
This was enhanced with a new loader component in #552. Please, try again.
