### ISSUE TITLE
Calendar UIs

### ISSUE THREAD

**Issue by AnkRaiza** [bespoken/dashboard#523]
### Expected Behavior
The calendar UI and positioning should be as per specs
![new-ui_cale](https://user-images.githubusercontent.com/11048365/34526088-4f246c9a-f06f-11e7-8ade-74f483a69ea9.jpg)

### Actual Behavior
current calendars are not according to specs

**Comment by robertonotte** [comment]
@AnkRaiza also this, please tell me how can I see it

**Comment by AnkRaiza** [comment]
for this ticket you need to login to the dashboard, then have some logs using the audio player with a skill, then the audio player tab should appear on the tabs menu, go to the audio session tab and you should be able to see it
