### ISSUE TITLE
Landing Page UIs

### ISSUE THREAD

**Issue by AnkRaiza** [bespoken/dashboard#524]
### Expected Behavior
Landing page look and feel should match new specs, create landing for login with amazon flow
![input_results-beforetoken](https://user-images.githubusercontent.com/11048365/34526256-f5f2d354-f06f-11e7-930a-e1344fc8ef9d.jpg)

### Actual Behavior
Landing page look and feel doesn't match new specs, there is no landing page for login with amazon flow

**Comment by robertonotte** [comment]
@AnkRaiza can you please list the step I should make in order to see it?

**Comment by AnkRaiza** [comment]
in order to test this ticket just login to the dashboard and you should see the amazon landing page flow (get vendorID step) after you confirm this i need to switch off the amazon flow, so you can see the other pages (logs, stats, validation, etc)

**Comment by robertonotte** [comment]
Dashboard on which URL?

**Comment by AnkRaiza** [comment]
dev-dashboard-bbcee.firebaseapp.com is the dev url, in the current flow all tickets should be testable on this url before creating a new release

**Comment by robertonotte** [comment]
Great, thanks man!

**Comment by robertonotte** [comment]
Already discussed with Pier by phone,  the work delivered doesn't meet the requirements.
No details included in order to save time as most of the differences between the graphics provided and the work delivered are very obvious.

**Comment by jperata** [comment]
for the number at the page, it was added so that we always knew which version is deployed. It's referenced in this issue:
https://github.com/bespoken/dashboard/issues/500
We can prioritize it in next sprint if we think is affecting the view, but should be a separate ticket. 
Is my opinion that it should not be shown on production, but we need additional feedback

**Comment by robertonotte** [comment]
Ok
