### ISSUE TITLE
Monitoring - Validation weekly report

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#536]
I believe this is left from Spint 4.
We already discussed, those that haven't had errors in validation will receive a weekly report confirming we have been looking over their skills. Specs already sent to Diego on Sprint 4.

**Comment by robertonotte** [comment]
@dmarvp As discussed:
Weekly email confirming that everything is fine is sent ONLY when:
 - user hasn't received any email notifying outages in the last 7 days;
 - user hasn't received any email notifying validation changes in the last 7 days.

Only email for this no report needed.

**Comment by dmarvp** [comment]
- This will go into a new project under the /monitor repository. The same way as the monitor and api folders already are. 
- We can handle this with a hyper cron job every week. 
- The idea is to get all sources that have validation or monitoring enabled per user. 
- Then query the "ping" table in dynamo to see if there have been outages or validation errors in the past week and send an email if not. 

Estimated time 2 days.

**Comment by dmarvp** [comment]
source-api#72 was created to get the sources with validation and/or monitoring enabled.
