### ISSUE TITLE
Monitoring - Generating basic HTML report

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#537]
Please note that the report will be changed on the next sprint, thus not to be considered as final.

Thus, this sprint scope is only about implementing the functionality of generating a basic HTML report; this report, however, will be finalized on the next sprint.

SAMPLE REPORT: https://drive.google.com/open?id=1ZcP1I6qJlybC4azsYomGgPi3HfjfWry6

**Comment by robertonotte** [comment]
@dmarvp, as discussed.
As a basic image, we can use the attached pdf drafted for validation. However, you can come up with a basic design by your own based on what is easy for you to create, and we will be improving this on Sprint 6. Alternatively, I can make something basic as well in jpg and send it to you.
Basically any way you feel more comfortable working with.

Let's make this only for Validation, optionally for outages as well.

**Comment by dmarvp** [comment]
per my discussions with @robertonotte , this will be implemented for the "UP" and "DOWN" mails received from the monitor. The goal is to turn the plain text emails into html that will be changed in the next sprints.
