### ISSUE TITLE
Dashboard - Landing+Validation

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#538]
FULL SPECS
https://docs.google.com/document/d/190bB8Xo72WoFopLOSYWUmeFJ_4JUcfddqq535wAdDyM/edit#

**Comment by dmarvp** [comment]
Need to clarify with @robertonotte the scope of this ticket before giving an estimate, since the specs show changes on the bespoken webpage, the dashboard landing page, also talks about an anonymous "Get started".

**Comment by robertonotte** [comment]
Had a call with Pier and Diego regarding this. Changed slidly the behaviour; specs updated.

**Comment by dmarvp** [comment]
Two tasks have been created out of this specs:
#588 and #589.

Once those are done, we can have the landing page defined here. It has to be done in coordination with @AnkRaiza when he finishes other needed components.

**Comment by dmarvp** [comment]
Addressed in different tickets by @AnkRaiza
