### ISSUE TITLE
Ability to Access the Secret Key After Skill Creation

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#54]
Currently, there isn't a way to get your secret key again after you created the skill.

**Comment by chrsdietz** [comment]
Could including this feature reduce security?  Could someone with a secret key they aren't supposed to have cause any trouble?

**Comment by michaelmyers** [comment]
If they are logged in, they should be able to view their secret key that is unique to their skill.  It will not be viewable if you are not logged in.

If somebody gets someones secret key they could potentially push logs to that skill.  We will need to make some enhancements on the server to allow for regenerating the keys if they become compromised or if the user wants to reset the key.  

At the moment, without this, the user will just create a new skill since it is only visible from the new skill page.

**Comment by michaelmyers** [comment]
The twilio pattern where you need to click to see the secret key should be our model. 
<img width="1194" alt="twilio" src="https://cloud.githubusercontent.com/assets/921356/20806487/f807470a-b7af-11e6-82ba-51209bf7f94e.png">
