### ISSUE TITLE
Validation: enable / disable monitoring

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#555]
There should be a switch at the top of the validation page to enable/disable monitoring. When doing so, we should validate if there have been changes to the script and tell the user to save them if needed. 

![image](https://user-images.githubusercontent.com/6411740/35343356-739a00dc-00f8-11e8-890e-cd90c2ac60cd.png)

The monitoring validation flag should go in: bespoken-tools/sources/< source >/validation_enabled

**Comment by AnkRaiza** [comment]
16hrs

**Comment by AnkRaiza** [comment]
This can be test by @jperata, use the validation page change the validation enabled button on any source, go to firebase db and check that your source has the validation enabled flag on the source

**Comment by jperata** [comment]
After clicking on the button
<img width="1224" alt="screen shot 2018-02-12 at 10 30 11 am" src="https://user-images.githubusercontent.com/8781604/36104366-cfa4cc9a-0fdf-11e8-93aa-d7523612eebd.png">
<img width="455" alt="screen shot 2018-02-12 at 10 30 30 am" src="https://user-images.githubusercontent.com/8781604/36104372-d5193396-0fdf-11e8-9a26-7fc56c4610cd.png">

After disabling the validation
<img width="470" alt="screen shot 2018-02-12 at 10 31 44 am" src="https://user-images.githubusercontent.com/8781604/36104496-347aeff0-0fe0-11e8-96eb-5aafb4d69f41.png">
