### ISSUE TITLE
Validation - Sprint4 Feedbacks

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#572]
Those are the feedback left on the Validation page that we couldn't integrate on Sprint 4.

**Comment by AnkRaiza** [comment]
is this for https://docs.google.com/document/d/1tL-Z3mAYDITKfSjyzFvTE-3Bh9VXvGfF0G6-dviRtAk/edit?ts=5a81cfbe#heading=h.mh0z3m1k3q5d

**Comment by robertonotte** [comment]
Yes Pier
