### ISSUE TITLE
Validation & Integration Banner

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#653]
From the Validation screen I can still see the right banner "unleash the beast" even if I'm already logged in.

Indeed whatever the menu is showing (check stats and check logs) that means the user has already completed the integration, thus banner asking for integrating shouldn't longer be there.

**Comment by robertonotte** [comment]
![bespoken-banner](https://user-images.githubusercontent.com/34077077/38505119-0be7b99c-3bdc-11e8-8ead-b6cfb572f586.jpg)

**Comment by robertonotte** [comment]
If the banner is placed due to technical problems (loading of elements causes crash) simple disable it showing instead a background with color #eef2f5

**Comment by dmarvp** [comment]
no longer relevant, the integration is going away
