### ISSUE TITLE
Back to Source

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#654]
From Validation screen user should be able to go back to the selected source screen from UI directly.

**Comment by robertonotte** [comment]
![bespoken-back](https://user-images.githubusercontent.com/34077077/38506268-fd422bc2-3bde-11e8-8278-7327a8652fea.jpg)

**Comment by AnkRaiza** [comment]
@jkelvie this should be "Back to list" right?

**Comment by jkelvie** [comment]
Yes
