### ISSUE TITLE
Dashboard Resizing

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#655]
This issue was reported by John, the dashboard looks bad when resized. I think the main problem is the menu (see screenshot). I wouldn't go too deep into it since we will be changing a little bit the design soon.

**Comment by robertonotte** [comment]
screenshot
![dashboard-resizing](https://user-images.githubusercontent.com/34077077/38506968-f1266c52-3be0-11e8-8e41-666b1d4bbf77.jpg)

**Comment by robertonotte** [comment]
I just realized that the right size for the all solution we have on here is by zooming at 80%, by doing this only some part of the text should be reviewed.

![bespoken-size](https://user-images.githubusercontent.com/34077077/38572602-261da938-3cb9-11e8-85fc-493626c62f41.jpg)

**Comment by AnkRaiza** [comment]
For now as we settle this fixes will apply to the most common screen resolutions: hd (1366 * 768), full hd (1920 * 1080) and 1440 * 900, all of this using browser zoom at 100%

**Comment by MKen-li** [comment]
Mark as verified:
Build: dev-57
Browser : Chrome
