### ISSUE TITLE
Add locale selector to validation page

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#657]
This will apply to the following languages and countries:

de-DE	German
en-AU	English (Australia)
en-CA	English (Canada)
en-GB	English (UK)
en-IN	English (India)
en-US	English (US)
fr-FR	French
ja-JP	Japanese

Screenshot attached.

**Comment by jkelvie** [comment]
Keep in mind - this can be different per skill. Once implemented, the monitoring piece will need to be updated as well to use the locale.

**Comment by robertonotte** [comment]
1. There is a usability issue: the last language is not that evident by looking a the list:
![image](https://user-images.githubusercontent.com/34077077/39272360-4d4bb362-48a1-11e8-8082-6ccb20f995e8.png). I'd suggest adding a scroll bar or we could just display them horizontally rather than vertically.
2. To really test them we need skills languaged base. I'm coordinating with Juan in order to have them and carry on the testing.
