### ISSUE TITLE
Visual Vs Editor

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#658]
YAML script editor on the validation page
1.	As an alternative to the regular UI
2.	A tabbed interface akin to WordPress Visual Editor/HTML editor that can be toggled between I believe makes sense

**Comment by robertonotte** [comment]
![visual](https://user-images.githubusercontent.com/34077077/38510803-b62cd77a-3beb-11e8-827a-c7673deb1c7a.jpg)

**Comment by dmarvp** [comment]
to be addressed in #701
