### ISSUE TITLE
Different tokens for different skills

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#660]
This issue was reported by John.

Use different tokens for different skills
1.	Another way to say it is, multiple tokens for a single Dashboard account
2.	We need Diego's input on this - perhaps there is a better way we can label the token so people can more easily understand what Alexa account they are associated with
3.	If a user has multiple tokens, they can select which one to use as a drop-down.

**Comment by dmarvp** [comment]
Closing this one, this is going to be included as part of the virtual devices manager tasks.
