### ISSUE TITLE
Remove Drop-down skill selection from Validation page

### ISSUE THREAD

**Issue by robertonotte** [bespoken/dashboard#668]
This ticket related to https://github.com/bespoken/dashboard/issues/654

As we have the selection of the skills from the top bar, John suggested to remove it from here.
![dropdown](https://user-images.githubusercontent.com/34077077/38748032-68aac1b8-3f12-11e8-90f1-06f156183ad8.jpg)

**Comment by jkelvie** [comment]
I think this should be a rename field instead - it's nice to be able to rename a skill, not just delete and re-add.

**Comment by robertonotte** [comment]
I don't see the possibility to rename the source name. 
![rename](https://user-images.githubusercontent.com/34077077/39271946-1cbe5cc8-48a0-11e8-8cdb-33770d011414.jpg)

**Comment by AnkRaiza** [comment]
do we want this to update the source name on each keystroke? it would be better to add a rename / save name button at the right, saving on each keystroke is not recomended as we are hitting a service everytime we do it.
