### ISSUE TITLE
Login page redesign

### ISSUE THREAD

**Issue by AnkRaiza** [bespoken/dashboard#709]

**Comment by GitBoHub** [comment]
Hi Pier! Here are some changes to the left side.
- Change button text to: Log in with Amazon
- Change button text to: Log in
- Change button text to: Log in with GitHub
- Reduce size of Or and Or
- Reduce size of Email Address and Password font
- Vertically center Reset Password and modify hover behavior to be more readable
- Add hyperlink to Bespoken logo and send to bespoken.io

Gracias!

**Comment by jperata** [comment]
![webinar](https://user-images.githubusercontent.com/8781604/41480607-996ad58c-7094-11e8-8687-c53109d4df10.png)
from Roberto, proposed image for the right screen
