### ISSUE TITLE
Update integration docs with new logging

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#717]
### Expected Behavior
New docs should reflect the current integration possibilities along our docs and reflect that you can now use logless-client. Also add the instruction for integration with ask-sdk 2.0 were you use the promise way.
<img width="658" alt="screen shot 2018-06-20 at 12 53 47 pm" src="https://user-images.githubusercontent.com/8781604/41878370-60805bbc-789a-11e8-9f47-f1c5c277cfff.png">

### Actual Behavior
Docs reflect the old way and misses v2.

### Reproduction Steps
Go to the integration tab in dashboard.

Duplicates #713

**Comment by jperata** [comment]
As part of https://github.com/bespoken/bst/issues/465, we need to check on this.

**Comment by ecruzado** [comment]
blocked until release a new version of dashboard

**Comment by jperata** [comment]
Marked as verified.
Build: dev-127
