### ISSUE TITLE
Virtual Device Management 

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#733]
### Summary

As a dashboard user, I want to be able to manage the different virtual devices I have set up so that I can test my skills with them.

### Acceptance Criteria

1. GIVEN: I'm a valid user using the dashboard.
WHEN: I click on the user's menu.
THEN: I see a new option "Virtual Devices" under "My account"

2. GIVEN: I'm a user already logged in.
WHEN: I click on the "Virtual Devices" option on the user's menu.
THEN: The virtual devices page appears and I see:
    - Three buttons: All, Alexa, Google (All is selected by default)
    - A label indicating the number of virtual devices associated to the user ( X/Y Virtual Devices ). Where X is the current number and Y the max number of virtual devices based on the user's plan.
   - A list of the virtual devices associated with the user's account. The list should include: Type, Token, Name, Creation Date, Copy and Remove buttons.
    - An "Add New" button at the bottom.
    
3. GIVEN: I'm on the Virtual Devices Page and I haven't reached my max number of virtual devices allowed as per my user plan.
WHEN: I click on the Add New button.
THEN: Two options appear: Alexa Virtual Device and Google Virtual Device.

4. GIVEN: I've clicked the Add button and I see the list of options.
WHEN: I click either of the Alexa or Google Virtual Device options.
THEN: A modal window/popup appears with an informative text *"In order to create a new Alexa/Google Virtual Device, you'll be asked to provide your Amazon/Google account credentials."* and Ok and Cancel buttons.

5. GIVEN: I'm on the Alexa/Google modal window (depending on my previous selection).
WHEN: I click on the Ok button.
THEN: I'm redirected to the Amazon/Google Login page for permissions. 

6. GIVEN: I'm on the Amazon/Google Login page for permissions.
WHEN: I give my permissions.
THEN: 
    - I'm redirected to the Virtual Devices page.
    - I see a new Virtual Device has been added to the list.
    - The new Virtual Device is called "Alexa Virtual Device" or "Google Virtual Device" by default.
    - The X/Y label increases by one.

7. GIVEN: I'm on the Virtual Devices Page and have at least one Virtual Device already created.
WHEN: I click on the Copy button next to a virtual device.
THEN: The token is copied to the clipboard (a visual confirmation should be given). We can use a Snackbar saying "The token for [Virtual device name] has been copied to the clipboard."

8. GIVEN: I'm on the Virtual Devices Tab and have at least one Virtual Device already created.
WHEN: I click on the remove button of a virtual device.
THEN: A confirmation modal/popup appears:
    - Text: Are you sure you want to remove this virtual device? Monitoring for any voice app using it will be disabled.
    - Ok and Cancel buttons.

9. GIVEN: The confirmation modal for removing a virtual device is open.
WHEN: I click on the OK button.
THEN: 
    - The virtual device is removed from the list of virtual devices.
    - The number of assigned virtual devices is updated.
    - Any voice app being monitored with this virtual device has monitoring disabled.
    - The virtual device token should be removed/disabled from the virtual device database too.
    - If possible, we should try to revoke our own access to that virtual device. (Investigate)

10. GIVEN: I'm on the Virtual Devices Page and I have reached the maximum amount of virtual devices per my plan.
WHEN: I click on Add a new Alexa or Google Virtual Device.
THEN: The Payment popup should appear (the same way we do on monitoring)

11. GIVEN: I'm on the Virtual Devices Page.
WHEN: I hover over a virtual device name.
THEN: I see a visual indication that the name can be edited.

12. GIVEN: I'm on the Virtual Devices Page.
WHEN: I click on a virtual device name.
THEN: The virtual device name becomes editable. The behavior follows the same pattern as when editing a source name.

13. GIVEN: I'm on the Virtual Devices Page.
WHEN: I click on one of the filter buttons: All, Alexa, Google
THEN: The virtual device list is updated with the proper selection.

### Resources
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/6411740/46548968-2c60ef80-c896-11e8-80a6-bd75dd742d01.png">

### NOTES
TBD.

**Comment by dmarvp** [comment]
@jperata @AnkRaiza on sprint 19, this task should be used to integrate #954 with https://github.com/bespoken/source-api/issues/130

**Comment by AnkRaiza** [comment]
@MKen-li this is also part of the changes from john's email 
- Title of page for virtual devices should Virtual Device Manager not Virtual Devices
- Names of the devies such as "alexa virtual device 1" -> capitalize the first letter of the words "Alexa Virtual Device 1"
- Say "Create Virtual Device" instead of "Get validation token" for user with no token on the validation page
- Change label from "Validation Token" to "Virtual Device" on the validation page
- Add hover on refresh icon on virtual device manager page that explains what it does
- When hovering on 3/3, explain what that represents or just write "3 (Created) / 3 (Available On Plan)"

**Comment by MKen-li** [comment]
Marked as blocked waiting for bugs:
https://github.com/bespoken/dashboard/issues/1005
https://github.com/bespoken/dashboard/issues/1002
https://github.com/bespoken/dashboard/issues/1001
https://github.com/bespoken/dashboard/issues/1000
https://github.com/bespoken/dashboard/issues/997
https://github.com/bespoken/dashboard/issues/998
https://github.com/bespoken/dashboard/issues/999

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-214
