### ISSUE TITLE
Validation Page UI issues

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#740]
Preconditions
Be on the validation page

Bugs

1. The space between text and background for the actual response is not consistent.
![actual response text-background](https://user-images.githubusercontent.com/39920441/43027924-6abe5c26-8c42-11e8-9eeb-01de9ca2c0b5.png)
When the text is to long we displayed "..." and the space between that and the background is also different
![actual response text-background2](https://user-images.githubusercontent.com/39920441/43027969-b1b560b6-8c42-11e8-8ecb-9d0826beff5a.png)

2. When you select from the auto complete the text box changes to yellow. 
![yellow background](https://user-images.githubusercontent.com/39920441/43027993-d6209182-8c42-11e8-8093-4eb67989fe5b.png)

3. The information tool tip for the monitoring shouldn't be clickable and the cursor shouldn't change.
https://media.giphy.com/media/1FEbMiwsyv10i4vh7T/giphy.gif

4. The copy space for the actual response is way to big, it should only allow to copy inside the gray area of each response
https://media.giphy.com/media/t7u32JWYwugqR2fWnl/giphy.gif
As the image show 

5. Set as disabled the options that aren't currently working like google actions or hybrid source.
![disabled options](https://user-images.githubusercontent.com/39920441/43028256-7698dd4e-8c44-11e8-91b7-a006f9749760.png)

6. Change "Save script" to "Save".

Environment:

OS: Win
Browser Chrome
Version Dev-79

**Comment by AnkRaiza** [comment]
the second issue will remain unchanged since we decided this is a default browser behabior we want to keep

**Comment by MKen-li** [comment]
Mark as verified.
Build = dev-94
