### ISSUE TITLE
An error message is displayed when getting or refreshing a token in Validation Page

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#745]
Preconditions
Be on the validation page

Bugs

1. When getting the token the web returns to the source page.
2. When refreshing the token the web returns to the source page.
3. When trying to get or refresh a token and click cancel we show "An error occurred. Please try again later."

Screenshots:
![token error](https://user-images.githubusercontent.com/39920441/43025804-c5872b10-8c38-11e8-9752-0ebc751f17e3.PNG)

OS: Win
Browser Chrome
Version Dev-79

**Comment by dmarvp** [comment]
https://github.com/bespoken/virtual-device/issues/131

Has been deployed to dev, @AnkRaiza you can now send a return_url query string parameter to the link_account virtual_device endpoint that will let it know where to redirect after creating the new virtual device token.

**Comment by MKen-li** [comment]
Mark as verified
Build = dev-90
