### ISSUE TITLE
Payment Feature

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#746]
### Summary

As a User of Dashboard, I want to be able to subscribe to a better plan so that I can have more features enabled in the system.

### Acceptance Criteria

1. GIVEN: I'm a user on the validation page and I click on the "Enable monitoring" button.
WHEN: I've reached the monitoring limits of my current plan.
THEN: I see a modal window (Screen 1) with the following:
    - A side panel with a llama saying "Oops!"
    - "You have reached the maximum number of monitored voice apps allowed by your subscription."
    - "To monitor additional voice apps, select a new plan."
    - "No, thanks" and "See plans" buttons.
    - An "x" icon on the top right corner.

*NOTE:* At any given time, clicking outside the modal window, at the "X" icon or in the "No, thanks" buttons in this or the following screens will close the modal window.

#### Screen 1
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/6411740/44551887-1932ff80-a6ee-11e8-83d0-d411c94306d4.png">

2. GIVEN: I'm on Screen 1.
WHEN: I click on the "See plans" button and *I'm currently on the "Free plan".*
THEN: The modal window shows (Screen 2):
    - A side panel with a llama saying "Choose the plan that's right for you"
    - Three sections detailing the different subscription plans (see Screen 2 mockup)
    - Each section should be selectable (eg. by a radio button). 
    - The Enterprise plan should have a "Contact us" button (disabled until Enterprise is selected)
    - "No, thanks" and "Continue" buttons. The continue button should be disabled by default and only enable when selecting Standard or Pro plans.

3. GIVEN: I'm on Screen 2.
WHEN: I'm currently on the "Standard" or "Pro" plans
THEN: 
    - The current plan should be selected but the Continue button should only enable if a bigger plan is selected. Lower plans are not selectable.

4. GIVEN: I'm on Screen 2.
WHEN: I select the "Enterprise" plan.
THEN: 
    - The "Contact us" button is enabled.
   
#### Screen 2
<img width="670" alt="image" src="https://user-images.githubusercontent.com/6411740/43809995-1e2480a6-9a7b-11e8-9daa-ee28f52a92c0.png">

5. GIVEN: I'm on Screen 2, I have selected the Standard or Pro plan.
WHEN: I click on the "Continue" button.
THEN: The modal window shows (Screen 3):
    - A side panel with a llama summarizing the contents of the selected plan, the price and that it will be changed to a credit card monthly.
    - "You are subscribing to a <selected plan> plan.
    - "Pay securely using your credit card"
    - Input fields for credit card data. Ideally, we would use something like http://kenkeiter.com/skeuocard/ or similar for React.
    - "See plans", "No, thanks" and "Subscribe now" buttons. 
    - The subscribe button should only be enabled when the credit card data is complete.
    - The see plans button would take the user to the previous modal, applying the same AC's described earlier (Screen 2).

#### Screen 3
<img width="660" alt="image" src="https://user-images.githubusercontent.com/6411740/43815032-3800dc82-9a93-11e8-9ef3-b646f7b3e821.png">

6. GIVEN: I'm on Screen 3, I have entered my credit card data.
WHEN: I click on the "Subscribe now" button and there is an error with the submitted data.
THEN: 
    - An error message explaining what happened should appear under the credit card input.
    - The data is not saved and the user remains on the same screen so that he can change the credit card or fix the data that was wrong.

~~7. GIVEN: I'm on Screen 3.
WHEN: I'm already subscribed on a plan and thus my credit card data is already in the system.
THEN: 
    - My credit card data should be preloaded (masked)
    - The Subscribe button should be enabled.~~
   
8. GIVEN: I'm on Screen 3, I have entered my credit card data.
WHEN: I click on the "Subscribe now" button and there is no error with the submitted data.
THEN: The modal window shows (Screen 4):
    - A side panel with a llama saying "Success!"
    - "Enjoy the benefits of your new <selected plan> plan.
    - A summary of what's included in the new plan
    - The user's next billing date
    - "Remember, you can change your plan anytime from your account page."
    - An "Ok" button. 

#### Screen 4 
<img width="658" alt="image" src="https://user-images.githubusercontent.com/6411740/43815378-0f3b9ca4-9a95-11e8-8ada-e9b84f6c6cdb.png">
    
9. GIVEN: I'm on Screen 4.
WHEN: I click on the "Ok" button 
THEN: 
    - The modal window closes.
    - The plan is updated for the current user.
    - The monitoring and logging limits are increased as per the user's new plan.

10. GIVEN: I'm on Screen 2, I have selected the Enterprise plan.
WHEN: I click on the "Contact us" button.
THEN: The modal window shows (Screen 5):
    - A side panel with a llama saying "Let's get in touch!".
    - "Contact us!."
    - "Tell us about your development and testing needs, and we will get in touch with you shortly."
    - An optional text input for the user to send a custom message. 
    - "See plans" (will take the user to the previous screen), "No, thanks" and "Send" buttons. 

#### Screen 5
<img width="652" alt="image" src="https://user-images.githubusercontent.com/6411740/44552063-a2e2cd00-a6ee-11e8-81f1-1f7ed1980479.png">

11. GIVEN: I'm on Screen 5.
WHEN: I click on the "Send" button.
THEN: 
    - An email is sent to sales@bespoken.io
        - The subject is *TBD.*
        - The body is filled with the text input content.
    - The modal window shows (Screen 6)
        - A side panel with a llama saying "Success!".
        - " Thanks for contacting us!"
        - "A Bespoken representative will get in touch with you in no time."
        - An "Ok" button. Clicking it will close the modal.
   
#### Screen 6
<img width="648" alt="image" src="https://user-images.githubusercontent.com/6411740/43817305-5c03edda-9a9e-11e8-99a9-a0a48c6fe816.png">

### NOTES
@jperata I think that for implementing things like AC2 or AC5 we should consider saving the plans and their benefits in firebase. So that they can be read and shown easily in multiple pages and limits can be applied programmatically without hardcoding.  

For the completion of this feature, the related issues are:
#705 , #706 , #704 , #739, #741, bespoken/stripe-api#11,
, bespoken/stripe-api#1, bespoken/stripe-api#3, bespoken/stripe-api#7, bespoken/stripe-api#10, 
bespoken/source-api#101

**Comment by MKen-li** [comment]
Moves to QA Rejected until the bugs are fixed : 
https://github.com/bespoken/dashboard/issues/750
https://github.com/bespoken/dashboard/issues/749
https://github.com/bespoken/dashboard/issues/748

**Comment by MKen-li** [comment]
Marked as blocked, waiting for bug fix.
https://github.com/bespoken/dashboard/issues/800
https://github.com/bespoken/dashboard/issues/797

**Comment by dmarvp** [comment]
Updated:
AC1
- Added the "x" icon to close the modals (on all of them)
- Changed the wording to reflect that the monitored voice apps limits have been reached.
AC11
- Added "See plans" button.

**Comment by MKen-li** [comment]
Marked as verified
Tickets found during Test fest (they will be fixed and tested on the next sprint)
https://github.com/bespoken/dashboard/issues/817
https://github.com/bespoken/dashboard/issues/819
https://github.com/bespoken/dashboard/issues/816
https://github.com/bespoken/stripe-api/issues/19
https://github.com/bespoken/dashboard/issues/820
https://github.com/bespoken/dashboard/issues/820
https://github.com/bespoken/dashboard/issues/821
