### ISSUE TITLE
The back navigation button sends the user to the login page [Payment Plan Page]

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#748]
**Preconditions**
Log in to the system.

**Steps To Reproduce**
1. Click "Upgrade Plan"
2. Click the Back navigation button

**Expected behavior**
The system should go back to the previous page

**Actual behavior**
The system regardless of the previous page it goes back to the Login Page

**Screenshots**
https://media.giphy.com/media/euGIouGTHSObOCe2vP/giphy.gif

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-84

**Additional context**

**Comment by AnkRaiza** [comment]
This fix will remove some odd links adding url to the browser history, the current behavior for dashboard is to bea single page application therefore only 1 url should be on the browser history (navigation should occur be using applicaton buttons and not back and forward buttons on the browser)

**Comment by MKen-li** [comment]
Mark as verified
Build = dev-90
