### ISSUE TITLE
The actual result message is displayed after changing the source

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#757]
**Preconditions**
Have more than 1 source created in dashboard

**Steps To Reproduce**
1. Log in to the system
2. Select a source 
3. Go to Validation Page
4. Run a script
5. Change source

**Expected behavior**
The Validation Page show the script if there is one created for the selected source

**Actual behavior**
The Validation Page show the previous actual result message

**Screenshots**
https://media.giphy.com/media/9G1xMlJvdZ6XqMKkIC/giphy.gif

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-87

**Additional context**
None.

**Comment by dmarvp** [comment]
Marked as verified.
Build: dev-127
