### ISSUE TITLE
Enable or disable payment based on an environment variable.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#758]
related to #746 

While the payment feature is completed, we must be able to disable everything related to it in production. Do this by creating an ENV variable called ENABLE_PAYMENT (default = False). 

If false: 
- The payment bar should not display.
- Monitoring limits and any other limits based on user plans should not be enforced.

Please be sure to use this environment variable instead of just looking at if the deploy was made to prod or dev.

**Comment by MKen-li** [comment]
Move to QA Rejected.

1. The label is disable but the validations per plan are still in place.
![validation pricing](https://user-images.githubusercontent.com/39920441/43612463-089fc9f0-9672-11e8-90b0-66dc0ed51c47.png)

2. The buttons and drop down section have to much vertical white space.

**Comment by MKen-li** [comment]
Mark as verified,
Build = dev-92
