### ISSUE TITLE
YAML Editor - hide when in prod

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#762]
Until the scope and final design of the YAML editor are defined, we should not show this feature in prod. Put in a condition that makes it invisible in prod. The screen should look the same way as it was before the YAML editor was introduced (that means no tab for "Visual" editor).

**Comment by dmarvp** [comment]
Since this is only for prod, please provide a screenshot of how it looks once development is completed.

**Comment by MKen-li** [comment]
Mark as blocked, waiting for deploy

**Comment by MKen-li** [comment]
Mark as verified,
Environment = "Staging" 
URL = https://dev-bespoken-tools.firebaseapp.com/dashboard/login
