### ISSUE TITLE
"My account" page

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#774]
### Summary

As a user of the dashboard I would like to have a page where I can manage my account.

### Acceptance Criteria

1. GIVEN: I'm a valid user of the dashboard.
WHEN: I log in onto the dashboard.
THEN: 
- I see two fields before to the user icon:
    - Line 1: My email (lower case, bold, don't shorten the email)
    - Line 2: Current plan: <name of the user's current plan> (the first letter must be a capital, regular, not bold or italic)
**NOTE:** Line 2 won't show until the payment feature has been enabled across Dashboard.
    - Both lines should be right aligned

- I see three clickable dots next to the user icon.

    <img width="195" alt="image" src="https://user-images.githubusercontent.com/6411740/44221888-8b34a300-a148-11e8-925c-aa17244cf38f.png">

2. GIVEN: I have logged in onto the dashboard.
WHEN: I click on the three dots icon.
THEN: A menu is displayed it contains the following items:
    - My Account (link to /account)
    **NOTE:** This link won't appear until payment has been enabled across Dashboard.
    - Read the Docs (link to https://read.bespoken.io)
    - Report an Issue (link to https://github.com/bespoken/dashboard/issues/new?template=bug_report.md)
    - Talk to Us in Gitter (link to https://gitter.im/bespoken/bst)
    - Log out 

    **NOTE**: Make sure that Read the Docs, report an issue and talk to us in gitter options open the links in a *new tab*.
    <img width="215" alt="image" src="https://user-images.githubusercontent.com/6411740/44222128-39404d00-a149-11e8-8d75-5e6cd3ae22c8.png">

3. GIVEN: I have opened the user menu.
WHEN: I click on "My Account"
THEN: The "My Account" page is displayed. 
I see the following: 
    - Title: My Account
    - "User Details" section containing:
        - Email
        - "Change my password" link.
 **NOTE**: Change my password is out of scope for this ticket.
        - "Delete my account" link (mailto: support@bespoken.io)
    - "Subscription" section containing
        - Current plan
        - More info link (https://bespoken.io/blog/)
        - Next billing date 
**NOTE:** Next billing date won't appear if the current plan is the Free plan
        - Want to change your plan? label
        - Contact us link (mailto: sales@bespoken.io)
    - "Payment Information" section containing
        - Credit card: VISA/Master Card/etc ending in XXXX label
        - An "Edit" link 
 **NOTE**: Edit link is out of scope for this ticket.
        - Exp date label
**NOTE:**  If no credit card is present, only show a label "No credit card registered." under Payment Information.
   

### Additional Resources
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6411740/44222512-5a556d80-a14a-11e8-8c16-c3c684f00950.png">

**Comment by dmarvp** [comment]
@daisyzarzo I updated the AC2 to include the: "report a bug" and "talk to us in gitter" options. Also, the menu should appear when hovering over the user's icon, instead of when clicking.

**Comment by dmarvp** [comment]
Updated the AC's and Screens with the latest changes done while in development.

**Comment by daisyzarzo** [comment]
Some Observations after the implementation

In the point 2:
![image](https://user-images.githubusercontent.com/36684960/44222271-a0f69800-a149-11e8-8c31-a9a965bf3515.png)
 It wasn't implemented, it is working as always

In the point 3:
![image](https://user-images.githubusercontent.com/36684960/44222359-da2f0800-a149-11e8-9ed0-cf75c99137b2.png)
* delete my account is linking to support@bespoken.io

*When the current plan is FREE, points A, B and C are not displayed, and on the payment side the following message is displayed: "No credit card was registered"

![image](https://user-images.githubusercontent.com/36684960/44222528-680af300-a14a-11e8-8395-23dd471f03ef.png)

**Comment by MKen-li** [comment]
Ticket marked as blocked until the reported issues are fixed.
https://github.com/bespoken/dashboard/issues/789
https://github.com/bespoken/dashboard/issues/790
https://github.com/bespoken/dashboard/issues/791

**Comment by MKen-li** [comment]
Status still in blocked but for this new 2 issues:
https://github.com/bespoken/dashboard/issues/803
https://github.com/bespoken/dashboard/issues/802

**Comment by MKen-li** [comment]
All bugs are fixed, marked as blocked until the Payment feature is completed

**Comment by MKen-li** [comment]
Mark as verified
Build = dev-104
Integration with payment will be tested in https://github.com/bespoken/dashboard/issues/805
