### ISSUE TITLE
The steps are blocked for an old amazon skill 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#777]
**Preconditions**
Use an account that has an old skill created.

**Steps To Reproduce**
1. Select the old source
2. Go to "Validation"

**Expected behavior**
The page is displayed without the gray area

**Actual behavior**
The gray area appear in the step section for the Amazon skill.

**Screenshots**
![block area](https://user-images.githubusercontent.com/39920441/43853982-38ee44a8-9b07-11e8-8365-a74e0af0706c.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-96

**Additional context**
This issue only happens when the skill created is very old. it cannot be reproduce with a new skill.

**Comment by AnkRaiza** [comment]
fixed on https://dev-dashboard-bbcee.firebaseapp.com/dashboard/, release dev-98

**Comment by MKen-li** [comment]
Verified in dev-98
