### ISSUE TITLE
The length of the source name shouldn't be infinite 

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#780]
**Preconditions**
Log in to the system.

**Steps To Reproduce**
1. Create a source
2. Enter 300 chars.
3. Save

**Expected behavior**
1. The maximum characters allow is 50.
2. The maximum characters displayed in Source Page is 20 (add 3 dots and add hover to see whole name)
3. The 50 characters are displayed in Validation Page

**Actual behavior**
The text goes beyond the field in all the areas that the source name is displayed.

**Screenshots**
![long name1](https://user-images.githubusercontent.com/39920441/43866727-6cdece02-9b2c-11e8-8034-3024a72050c8.png)
![long name 2](https://user-images.githubusercontent.com/39920441/43866728-6cf6dea2-9b2c-11e8-92ca-4a929316317f.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-96

**Additional context**
None.

**Comment by MKen-li** [comment]
Back to dev
Build = dev-109
![long name](https://user-images.githubusercontent.com/39920441/44681985-c4ea9100-aa07-11e8-9cbb-b780bb660c48.png)

**Comment by MKen-li** [comment]
Moved back to dev the hover pen icon is not matching the name length

**Comment by dmarvp** [comment]
@MKen-li can we handle that small issue in another bug and close this one? I think it only happens when the name has more than 45 characters.

**Comment by MKen-li** [comment]
Marked as verified
Build dev-144
the hover icon issue will be fix in this ticket https://github.com/bespoken/dashboard/issues/825
