### ISSUE TITLE
The current plan label doesn't show the correct plan

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#791]
**Preconditions**
Select a user that has any plan that is not Free.

**Steps To Reproduce**
1. Click the 3 dots button
2. Select My account option

**Expected behavior**
The Current plan label displays the correct one.  

**Actual behavior**
The Current plan label is set to Free.

**Screenshots**
![my account plan](https://user-images.githubusercontent.com/39920441/44289619-ab448f00-a23a-11e8-8a70-e2b87d928260.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-MyAccount

**Additional context**
None.

**Comment by daisyzarzo** [comment]
the reason is that StripeApi has a new endpoint(getCreditCardInformation ), which is not yet deployed because it needs some tests,

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-103
