### ISSUE TITLE
Buttons on payment modals are hidden when lowering the resolution

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#816]
**Preconditions**
Have enough monitored skills to get the payment modal opened when enabling one more.

**Steps To Reproduce**
1. Go to Validation on a source
2. Click on Enable monitoring
3. Click on See Plans
4. Choose the Standard or Pro plans and go to the next screen
5. Reduce the size of the screen or zoom it to 125%.

**Expected behavior**
The modal should keep showing the buttons correctly.

**Actual behavior**
The buttons are hidden and can't be reached.

**Screenshots**
![image](https://user-images.githubusercontent.com/6411740/44818404-9eb32580-abae-11e8-8074-8f44855befb4.png)

**Environment:**
 - OS: OSX.
 - Browser: Chrome

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-115
