### ISSUE TITLE
Email and plan label are not aligned correctly.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#818]
**Preconditions**
Be in the Standard or Enterprise plans.

**Steps To Reproduce**
1. Enter into dashboard.

**Expected behavior**
I can see my email and plan next to my user icon and they are right aligned.

**Actual behavior**
Labels are left aligned.

**Screenshots**
<img width="295" alt="image" src="https://user-images.githubusercontent.com/6411740/44818874-1df52900-abb0-11e8-9414-99ab9875baec.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/6411740/44818897-306f6280-abb0-11e8-9494-2b3709801a03.png">

**Environment:**
 - OS: OSX
 - Browser: Chrome

**Additional context:**
It works for both Free and Pro plans.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-115
