### ISSUE TITLE
Console errors "No such plan: Enterprise"

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#819]
**Preconditions**
Have enough monitored skills to get the payment modal opened when enabling one more.

**Steps To Reproduce**
1. Go to Validation on a source
2. Click on Enable monitoring
3. Click on See Plans
4. Select the enterprise plan

**Expected behavior**
Everything works as expected.

**Actual behavior**
A console error appears:
[Error] Failed to load resource: the server responded with a status of 500 (No such plan: Enterprise) (plan, line 0)
[Error] Unhandled Promise Rejection: Error: No such plan: Enterprise
	step (dashboard.js:177873)
	rejected (dashboard.js:177844)
	promiseReactionJob

**Screenshots**
<img width="1554" alt="image" src="https://user-images.githubusercontent.com/6411740/44819014-b9869980-abb0-11e8-8ec8-34a5fc80dfe0.png">

**Environment:**
 - OS: OSX
 - Browser Chrome / Safari

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-115
