### ISSUE TITLE
Contact email when selecting an Enterprise plan is not being sent

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#820]
**Preconditions**
Have enough monitored skills to get the payment modal opened when enabling one more.

**Steps To Reproduce**
1. Go to Validation on a source
2. Click on Enable monitoring
3. Click on See Plans
4. Select "Enterprise"
5. Click on "Contact us"
6. Follow the steps until the end

**Expected behavior**
The configured email account should get an email containing the message sent by the user.

**Actual behavior**
No email is being sent.

**Environment:**
 - OS: OSX.
 - Browser: Chrome

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-119
