### ISSUE TITLE
Technical change: Recover plan details from firebase.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#823]
From: https://github.com/bespoken/dashboard/issues/793#issuecomment-416724794

We need to:

1. Get rid of the environment variables where we store the logs limitations: 
> process.env.STANDARD_LLN
> process.env.FREE_LLN
> process.env.PRO_LLN

2. Instead, use a new structure in firebase called "plans" inside firebase. E.g.:

```json
{
  "plans": [
    {
      "id": "free",
      "displayName": "Free",
      "benefits": {
        "monitoredSkills": 1,
        "logs": 1000000,
        "virtualDevices": 1
      }
    },
    {
      "id": "standard",
      "stripePlanId": <stripePlanId>,
      "displayName": "Standard",
      "benefits": {
        "monitoredSkills": 3,
        "logs": 10000000,
        "virtualDevices": 1
      }
    },
    {
      "id": "pro",
      "displayName": "Pro",
      "stripePlanId": <stripePlanId>,
      "benefits": {
        "monitoredSkills": 10,
        "logs": 50000000,
        "virtualDevices": 1
      }
    },
    {
      "id": "enterprise",
      "displayName": "Enterprise"
    },
  ]
}
```

3. for each user, add a new property "planId" (whenever the user changes plans) and benefits (for enterprise users **only**). E.g.:
```json
{
"user": {
  "id": <user_id>,
  "planId": <planId from the firebase plans collection>,
  "benefits": {
        "monitoredSkills": 50,
        "logs": 3000000,
        "virtualDevices": 15
      }
}
```

4. When login into the dashboard, we should:
    - Internally, retrieve the plan name and benefits from the plans collection (by planId)
        - Plan name is shown next to the user icon, and inside "My account".
    - If the user is an enterprise one, retrieve the benefits from it's own user object
    - Apply the limitations of those benefits inside the dashboard per user
    - If the user does not have the planId property, assume the user is in a free plan.

5. When opening the payment modal:
    - Plan names should come from the plans collection
    - The listed plan benefits should come from the benefits object of each plan

**NOTES**
- We won't be saving/using the ``stripeSubscribedPlanName`` property at the user level, since this would prevent us from changing the name of a plan globally. Instead, we will tie the user to a plan by a ``planId``.
- The other two properties from stripe on the user object (related to customer id and the stripe subscribed plan id) can remain there.
- The ``striplePlanId`` property on the plans (name can vary) should reflect the identifier sent to stripe when subscribing a user to a plan.

**Comment by dmarvp** [comment]
@jkelvie @jperata this ticket needs triage from you before adding it to the sprint backlog. Please review and let me know your thoughts.

**Comment by jkelvie** [comment]
Why do we store the benefits of the plan on the user's object? Why not just get this from the master plan list?

**Comment by dmarvp** [comment]
@jkelvie we'll do that for enterprise user's only, since we want to be able to customize the number of virtual devices / logs / monitored skills. All the other users get their benefits from their current plan.

**Comment by jkelvie** [comment]
Okay, I see - that makes sense to me and is a useful feature. Also, is the virtualDevice limit enforced?

With regard to the log limits:
For the standard plan, it should be 10,000,000
For pro, it should be 50,000,000

**Comment by dmarvp** [comment]
Updated the logs number on the ticket and moved it to the Sprint Backlog.

**Comment by jperata** [comment]
Seems to be failing along https://github.com/bespoken/dashboard/issues/831 , need verification and fixes

**Comment by jperata** [comment]
Marked as verified
Dashboard build: dev-128
