### ISSUE TITLE
The edit button area is shorter than the text box

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#825]
**Preconditions**
log in to the system.

**Steps To Reproduce**
1. Create a source with the max number of characters
2. Hover through the whole text

**Expected behavior**
The edit box and pen icon are show if the mouse is hover in all parts of the text box

**Actual behavior**
The edit button area is shorter than the text box

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-144

**Additional context**

**Comment by dmarvp** [comment]
Moving back to in Dev. Seems to be working correctly on Chrome and Safari, but the pencil icon does not appear in Firefox.

Also: can we add some space between the pen icon and the source name?

![sep-11-2018 22-32-59](https://user-images.githubusercontent.com/6411740/45400683-bb217a00-b612-11e8-9f50-b08d159452ca.gif)

**Comment by dmarvp** [comment]
Verified in dev-129.
