### ISSUE TITLE
Outage notifications have incorrect instructions

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#827]
**Steps To Reproduce**
1. Go to the skill -> settings page
2. Look at the text

**Expected behavior**
The text should say:
```
Enabling “Outage Notification” will:
* Ping the service at a five-minute interval (by default with an empty JSON payload)
* Notify the registered email address if the service does not respond
* Enable custom JSON to tailor the JSON payload
```
**Actual behavior**
The actual text is different, and incorrectly states a 1-minute interval.

It also has grammatical errors that should be fixed.

**Comment by dmarvp** [comment]
Marked as verified.
Build: dev-127
