### ISSUE TITLE
Log limit email is not being sent

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#831]
**Preconditions**
Log in to the system

**Steps To Reproduce**
1. Select an skill and complete the integration process
2. Generate logs until you pass the limit per plan
3. Interact with dashboard 

**Expected behavior**
The warning email is sent

**Actual behavior**
The email is not sent

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-120

**Additional context**

**Comment by jperata** [comment]
Seems like it's only counting the logs at the moment if validation is enabled.

**Comment by jperata** [comment]
Not working for 6 logs for a free user 
juan+payment@bespoken.io 
sourceid: de21da37-ac39-419c-babc-8ac58931ac61

**Comment by jperata** [comment]
Seems like the change to get the benefits from the database is part of the issue, was at the time of the test at 1 million, reduced it to 4 , but it still failed.

**Comment by jperata** [comment]
Marked as verified
Dashboard build: dev-128
