### ISSUE TITLE
My account layout change

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#847]
### Summary

As a user, I want to see the different sections of my account page in an optimal way across different displays.

### Acceptance Criteria

1. GIVEN: I'm a user logged in Dashboard.
WHEN: I click on the "My account" link
THEN: I see the following sections:
    - User details
    - Subscription
    - Payment Information
One next to the other (horizontal) instead of one below the other.
 
2. GIVEN: I'm on the "My account" page.
WHEN: I change the size of my current window.
THEN: The sections start to stack one below the other (the same way they are currently) for an easy viewing. The order is the same:
    - User details
    - Subscription
    - Payment Information
### Additional Resources

* Sections in my account next to each other
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/6411740/45196321-48cf2500-b221-11e8-8d19-f50c79e92fed.png">

**Comment by dmarvp** [comment]
Sent back to dev with some minor style changes.

**Comment by MKen-li** [comment]
Blocked waiting for https://github.com/bespoken/dashboard/issues/868

**Comment by MKen-li** [comment]
Marked as verfied
Build dev-138
