### ISSUE TITLE
My account plan limits overview

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#848]
### Summary

As a user of the dashboard
I want to see how much of my current plan benefits I have consumed
so that I can take the necessary actions

### Acceptance Criteria

1. GIVEN: I'm a user in dashboard.
WHEN: I click on the "My account link"
THEN:
- I see in the "Subscription" section, under the current plan:
    - Logs captured this month: "number of logs captured this month"/"number of logs allowed by my current plan"
    - Monitored voice apps: "number of monitored voice apps"/"number of monitored voice apps allowed by my plan"
    - Virtual devices: 1/"number of virtual devices allowed by my plan"
- The "Next billing date" label has been moved to the end of the "Payment information" section.

### Additional Resources
<img width="1076" alt="image" src="https://user-images.githubusercontent.com/6411740/45196737-5685aa00-b223-11e8-8089-5c189ab78061.png">

### NOTES
We still need to decide on the best way to show the number of logs used currently. 
Alternatives:
- 50,000/1,000,000 
- 0.05M / 1M
- 0.05%

This needs to be done once #823 has been merged into master.

**Comment by MKen-li** [comment]
blocked waiting for https://github.com/bespoken/dashboard/issues/868

**Comment by MKen-li** [comment]
Marked as verfied
Build dev-138
