### ISSUE TITLE
Clicking on user's image should expand the menu

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#849]
### Summary

As a user of the dashboard
I want to click on my image and get the drop-down of account options
because that is intuitive for me

### Acceptance Criteria

1. GIVEN: The user has logged into the dashboard
WHEN: The user clicks on their photo in the top-right
THEN: The menu should drop-down, same as if they clicked the three dots
The menu should shown in the same position as if they clicked the three dots

**Comment by dmarvp** [comment]
Verified in Chrome, Safari and Firefox.
Build: dev-127
