### ISSUE TITLE
Validation UI layout changes.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#853]
### Summary

As a first step in integrating a YAML editor, we will change the layout inside the validation tab a bit. 

### Acceptance Criteria

1. GIVEN: I'm a user of Dashboard. 
WHEN: I select a source and click on the validation tab.
THEN: I see the following screen:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/6411740/45339310-91574d00-b557-11e8-8f46-dbda3461d7f3.png">

Main changes from the current version: 
- Language dropdown has been moved next to the platform dropdown. * It doesn't have flags anymore. *
- Validation token is now below the platform and laguage drop downs
    - It will only show the first two sections of the token (right before the second dash), followed by three dots.
    - The whole validation token can be seen as a tooltip (with the title attribute)
- Next to the validation token there is a clickable copy icon. Use the title attribute with "Copy"
- Next to the copy icon there's a clickable refresh icon. Use the title attribute with "Refresh"
- Monitoring icon size has been decreased.
- Wording for the monitoring has changed:
    - Monitoring enabled/Monitoring disabled depending on the current state.
- Save and Run Script buttons have been moved both below the ACTUAL column.
    - Only run has a primary color, save has not
    - "Run" button instead of "Run Script >"
- YAML Editor (beta) toggle under the monitoring icon. **Only visible if the YAML editor has been enabled in the system (prod and dev)**
- Info icon next to the toggle with the following text on hover: The YAML Editor (BETA) is a more powerful, advanced way of creating end to end tests. Learn more at https://read.bespoken.io

**Comment by jkelvie** [comment]
Looks good to me

**Comment by MKen-li** [comment]
Marked as blocked waiting for https://github.com/bespoken/dashboard/issues/869 and some other minor issues that Pier is working on

**Comment by MKen-li** [comment]
Marked as verfied
Build dev-138
