### ISSUE TITLE
Intercom integration for a single page app 

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#861]
### Summary
We need to do some tweaks for Intercom integration so that the onboarding can work as we expect it to.

### Acceptance Criteria

1. GIVEN: I'm a user in dashboard.
WHEN: I navigate trough Dashboard (going between tabs for example)
THEN: Tell intercom that the url has changed.

### Additional Resources
* https://www.intercom.com/help/install-on-your-product-or-site/other-ways-to-get-started/integrate-intercom-in-a-single-page-app

### NOTES
This is to support the onboarding process by @ig-perez

**Comment by MKen-li** [comment]
Marked as verified
This ticket was verified with the help of @ig-perez  as he is the one that knows the expected behavior
Build dev-144
