### ISSUE TITLE
My account: Name and Company update.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#864]
### Summary

As a user of Dashboard
I want to be able to edit details of my profile like name and company.

### Acceptance Criteria
1. GIVEN: I'm a user of Dashboard. 
WHEN: I go into My Account Page.
THEN: I see two new fields under User Details:
    - Name 
    - Company

**NOTES:**
    - Default values for both fields are just three dots (...)
    - Max length for both fields is 50 characters.

2. GIVEN: I hover the mouse over the name or company.
WHEN: The mouse is over any of those two fields.
THEN: The label changes from a label into an editable input.

3. GIVEN: I fill the input.
WHEN: I leave the input or press enter.
THEN: 
    - The input turns into a label again.
    - The change is saved into the database.

**NOTES:**
    - Default values for both fields are just three dots (...)
    - Max length for both fields is 50 characters.
    - No special signs should be typable e.g.: !@#$%^&*()+= etc.

4. GIVEN: I put empty values into the input.
WHEN: I leave the input or press enter.
THEN: 
    - The input turns into a label again.
    - The label should show the default value again.
    - The value should be removed from the database.

##### Mockups

<img width="1073" alt="image" src="https://user-images.githubusercontent.com/6411740/46320037-0c81b100-c5a2-11e8-8ecd-d15e6454fd30.png">

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/6411740/46320253-1eb01f00-c5a3-11e8-8fef-1f0543b4211d.png">

##### Example from another page
![oct-01-2018 17-57-07](https://user-images.githubusercontent.com/6411740/46320376-a5fd9280-c5a3-11e8-9a08-562c915457ee.gif)

**Comment by MKen-li** [comment]
Marked as blocked
Waiting for bug https://github.com/bespoken/dashboard/issues/911

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-160
