### ISSUE TITLE
The back to list is displayed when there is only one source

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#875]
**Preconditions**
Log in to the system.

**Steps To Reproduce**
1. Create a source

**Expected behavior**
The back to list is only displayed in any page except the Source page.

**Actual behavior**
The back to list is displayed in the source page when is only one source.

**Screenshots**
![back to list](https://user-images.githubusercontent.com/39920441/45783546-b4ef5700-bc2b-11e8-98b2-8dd96a18f6bf.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-135

**Additional context**
This issue is only presented in the dev enviroment, prod is as expected.

**Comment by daisyzarzo** [comment]
it seems like everything's works correctly

![image](https://user-images.githubusercontent.com/36684960/45823271-f37c2480-bcb2-11e8-9edc-e9f6309f7b58.png)
![image](https://user-images.githubusercontent.com/36684960/45823294-fecf5000-bcb2-11e8-932e-85b8913334a4.png)

**Comment by daisyzarzo** [comment]
maybe it was the last deploy that Pier did,
where he made some fixes for the url on the dashboard

**Comment by MKen-li** [comment]
Marked as verified
Build dev-138
