### ISSUE TITLE
Send extra fields (and update existing ones) to Intercom in order to better interact with users

### ISSUE THREAD

**Issue by ig-perez** [bespoken/dashboard#888]
### Summary
To improve our communications with the users and make them automatic we need to start sending extra fields from Dashboard to Intercom. We also need to remove some unused fields and remove some of them which at this moment don't provide complete information.

Please start sending these new fields to Intercom:
[ ] **userPlan**: A string containing the name of the user's current plan. Values might be Free, Standard, Pro or Enterprise. Dashboard needs to update this value every time there is a change in the plan for the user.

[ ] **numSources**: The total number of sources the user has created on Dashboard. Every time there is a change on this number in Dashboard, Intercom needs to be updated.

[ ] **numMonitoredSources**: The total number of sources with validation monitoring enabled. Each time a user enables/disables monitoring for a source, Intercom needs to be updated.

[ ] **userLogs**: The total number of logs generated by the user each month. This value should be sent to Intercom on a monthly basis, except when the number of logs has exceeded the threshold of user's current plan.

[ ] **numVirtualDevices**: The total number of virtual devices the user has created. Each time the user creates/deletes a virtual device, Intercom needs to be updated.

Also, please remove next fields:
[ ] **usingMonitoring**
[ ] **usingValidation**

### Acceptance Criteria
The feature request will be accepted after verifying all of these fields are populated on Intercom and are updated as described above.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-157
