### ISSUE TITLE
The focus should be in the new password when the passwords don't match

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#892]
**Preconditions**
Log in to the system.

**Steps To Reproduce**
1. Go to My Account Page
2. Click the Change password button
3. Enter a valid current password
4. Enter the new passwords so they don't match
5. Click the "Save" button

**Expected behavior**
The focus goes to the new password text field.

**Actual behavior**
The focus goes to the Current password text field

**Screenshots**
None.

**Environment:**
 - OS: Win 10 
 - Browser Chrome
 - Version dev-146

**Additional context**
None.

**Comment by daisyzarzo** [comment]
the focus is already on the current password 
in case the passwords  not match
![image](https://user-images.githubusercontent.com/36684960/46322151-f2999b80-c5ac-11e8-8228-a85e0abc2426.png)

**Comment by daisyzarzo** [comment]
is it necessary to erase the input in newPassword too?

**Comment by MKen-li** [comment]
Marked as verified
Build dev-147
