### ISSUE TITLE
Survicate support

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#901]
**Is your feature request related to a problem? Please describe.**
We need the ability to send custom surveys to our users through intercom.

**Describe the solution you'd like**
Integrate survicate with intercom and dashboard.

**Additional context**
Instructions can be found here (under manual tracking code installation): https://help.survicate.com/website-survey-installation/how-to-install-a-survey-on-the-website

**Comment by daisyzarzo** [comment]
this ticket was resolved in the following P-R
https://github.com/bespoken/dashboard/pull/925

**Comment by ig-perez** [comment]
Survicate released on Oct 24 a new version of the integration where it is not needed anymore to use the tracking code on within the <body> tag. This new integration has been tested on dev, and now there is no need to continue with this ticket. Please rollback changes. Thanks.
