### ISSUE TITLE
Monitoring on empty scripts

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#902]
**Preconditions**
Be a user of dashboard with a source created and validation monitoring enabled.

**Steps To Reproduce**
1. Remove your script completely.
2. Save.

**Expected behavior**
Monitoring should be disabled since we don't allow monitoring empty scripts.

**Actual behavior**
Monitoring remains enabled.

**Environment:**
 - OS: MacOS
 - Browser: Chrome, Safari

**Additional context**
The same thing happens in YAML monitoring.

**Comment by MKen-li** [comment]
Closing this ticket.
This functionality was already controlled by not allowing the user to save an empty test
