### ISSUE TITLE
(Enhancement) make the focus go to the source name field when creating a new source

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#923]
**Preconditions**
Log in to the system

**Steps To Reproduce**
1. Create a new Source

**Expected behavior**
The focus goes to the source text field.

**Actual behavior**
After creating a source the user has to click the source name.

**Screenshots**
None.

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-161

**Additional context**

**Comment by jricaldi** [comment]
@MKen-li I have some questions:

1. "Create a new Source" means "create a new skill"?
2. If I click or focus in "Skill name here" we won't have any placeholder. Do I need to insert a placeholder too?

**Comment by MKen-li** [comment]
1. Yes
2. After discussing, the expected behavior would be to have the focus in the skill name with a placeholder that will disappear when the user starts typing.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-200
