### ISSUE TITLE
The GitHub login is not working

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#928]
**Preconditions**
None.

**Steps To Reproduce**
1. Go to the login page
2. Click on login with GitHub

**Expected behavior**
The GitHub login page is displayed and the user can log in correctly.

**Actual behavior**
The user can't log in and the system displayed the message "Error returned trying to log in."

**Screenshots**
![login github](https://user-images.githubusercontent.com/39920441/47304655-da85cc80-d5ec-11e8-9530-89224d42f513.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-162

**Additional context**
None.

**Comment by dmarvp** [comment]
Apparently, it doesn't work in dev, but it does work in prod. Still, this is preventing QA from testing with a Github user in dev and should be fixed.

**Comment by jricaldi** [comment]
@dmarvp the fix is already deployed but we have another could affect this.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-199
