### ISSUE TITLE
[Login]Change the wrong formatted email message

### ISSUE THREAD

**Issue by MKen-li** [bespoken/dashboard#933]
**Preconditions**
None.

**Steps To Reproduce**
1. Go to the Login page
2. Click on the register button
3. Enter an invalid email
4. Enter the rest of the fields correctly
5. Click the Submit button

**Expected behavior**
The system displays the message "The email address is not a valid email" and the focus goes to the email text field.

**Actual behavior**
The system displays the message "Email [email entered] is not a valid email."

**Screenshots**
![email badly formatted](https://user-images.githubusercontent.com/39920441/47365444-2f831a80-d6a1-11e8-861a-f0a1180913ff.png)

**Environment:**
 - OS: Win 10
 - Browser Chrome
 - Version dev-162

**Additional context**
None.

**Comment by jricaldi** [comment]
@MKen-li do you want clear the field too?

**Comment by MKen-li** [comment]
no

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-199

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-200
