### ISSUE TITLE
Add support for es-ES, it-IT

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#948]
### Summary

As a user of the dashboard
I want to test my skills in a variety of languages
supported by Alexa

### Acceptance Criteria

1. GIVEN: I'm a user in Dashboard
WHEN: I go into the Validation tab
THEN:
I see the languages dropdown now has two more options:
    - Label: "Spanish (Spain)"  / Value: es-ES
    - Label: "Italian" / Value: it-IT
The options in the language dropdown are **alphabetically ordered by Label.**

2. GIVEN: I select one of the new languages.
WHEN: I enter a valid script. Eg. "Qué hora es?" / "che ore sono?" and click Run
THEN: Validation works correctly as expected.

### NOTES
For even further testing, please create an account in:
- [Amazon Spain](https://www.amazon.es)
- [Amazon Italy](https://www.amazon.it)

Create an account in Dasboard and create tokens for these two users. Then try opening an Alexa skill.

**Comment by MKen-li** [comment]
Marked as blocked
waiting for https://github.com/bespoken/dashboard/issues/963

**Comment by MKen-li** [comment]
Marked as verified,
the other issue will be resolved in the next sprint
