### ISSUE TITLE
After creating a virtual device token for a first time, validation says we still don't have one.

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#949]
**Preconditions**
Be a NEW user of the dashboard with a verified email.

**Steps To Reproduce**
1. Go to Validation.
2. Create a simple validation script and save it.
3. Get a new token.
4. Try to run validation.

**Expected behavior**
Validation works correctly.

**Actual behavior**
We get a snackbar saying that in order to run validation we must first get a token. It works correctly if we refresh the page.

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-189
