### ISSUE TITLE
Use Intercom-node for User deletion

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#951]
### Summary

As a User wanting to delete it's acount
I want it to be deleted also in Intercom

### Acceptance Criteria

1. GIVEN: I'm attempting to delete my user
WHEN: THe user is deleted
THEN: It's also deleted on intercom

### Additional Resources
https://github.com/intercom/intercom-node
### NOTES

Relates to #940

**Comment by dmarvp** [comment]
After discussing internally, we are not going to delete users from intercom for now. Closing this issue.
