### ISSUE TITLE
Change to yaml editor affects the counting on the weekly report

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#957]
**Preconditions**
Change a skill that includes monitoring from visual editor to yaml editor

**Steps To Reproduce**
1. Change a skill that includes monitoring from visual editor to yaml editor

**Expected behavior**
Test counts is similar to previous count

**Actual behavior**
Test counts stop counting once it goes to yaml

**Screenshots**
<img width="798" alt="screen shot 2018-11-05 at 3 47 31 pm" src="https://user-images.githubusercontent.com/8781604/48025692-23bc3d00-e112-11e8-9512-f42f8b1cdbba.png">

**Environment:**
 - OS: Mac
 - Browser: Firefox

**Additional context**
Test was done with guess the price, there was no errors on that run.

**Comment by jperata** [comment]
The ticket was returned to Dev since the email count of the issue was not validated.

**Comment by MKen-li** [comment]
Moving back to dev

**Comment by jperata** [comment]
With the monitor deployment to prod to support correctly yaml editor and fix visualization bugs. This was solved

Attaching evidence of the latest email sent for a source with yaml editor.
<img width="1225" alt="screen shot 2018-12-12 at 10 53 53 am" src="https://user-images.githubusercontent.com/8781604/49881389-3d7d2e00-fdfc-11e8-8b18-0df0400da800.png">

**Comment by MKen-li** [comment]
closing ticket
