### ISSUE TITLE
Pricing Page for Beta

### ISSUE THREAD

**Issue by michaelmyers** [bespoken/dashboard#96]
We want to mention the pricing page but stress that is it free during the beta and that we will always be committed to providing a free tier for hobbyist.  

This may need to be on the actual website and not the dashboard, in that case make sure we link to the pricing from within the dashboard.

**Comment by michaelmyers** [comment]
Should this go on the website and it just be a link from within the dashboard?

**Comment by chrsdietz** [comment]
What's the difference?  I would think we'd want to make a pricing version highly visible.

**Comment by michaelmyers** [comment]
Something like Slacks https://slack.com/pricing

**Comment by michaelmyers** [comment]
This is handled in https://github.com/bespoken/bespoken-tools-website/pull/51
