### ISSUE TITLE
Update my credit card

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#964]
### Summary

As a subscribed user of Dashboard
I want to be able to change my credit card number
so that I can continue my subscription

### Acceptance Criteria

1. GIVEN: I'm a subscribed user of the Dashboard
WHEN: I go into my account page
THEN:
- I see a link saying "Change" next to my credit card number

2. GIVEN: I'm a subscried user of the Dashboard on My account page
WHEN: I click on the "Change" link
THEN: A modal for changing my credit card appears.
- Title: Update my credit card
- Text: Pay securely for your Bespoken Dashboard subscription. Enter your new credit card number below: 
- A component to update the credit card. Use the same one we use on the payment modals.
- A Cancel and Update Buttons.
- An "x" at the top right corner.

3. GIVEN: I have the update credit card modal open.
WHEN: I click on the "Cancel" button or the "x" at the top right corner.
THEN: The modal closes, no changes are made.

4. GIVEN: I have the update credit card modal open.
WHEN: I enter a valid credit card and click on the update button.
THEN: 
- The credit card of the user is updated in stripe.
- Any new payment is charged to this credit card.
- The modal is closed.
- The credit card info on "My account" page is refreshed.

5. GIVEN: I have the update credit card modal open.
WHEN: I enter an invalid credit card and click on the update button. Or an error happens.
THEN: 
- No changes to the data are made.
- The modal is not closed.
- The corresponding error message should appear in a label below the credit card component (please follow the same validations/error messages from the payment modal).

### Additional Resources

<img width="1078" alt="image" src="https://user-images.githubusercontent.com/6411740/48867089-0a1e2500-eda3-11e8-98b1-fd8d3eb88eb8.png">

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/6411740/48869919-e95acd00-edac-11e8-8c51-3a7e3ddd43ec.png">

### NOTES

[Some complementary notes if necessary:]

**Comment by daisyzarzo** [comment]
![image](https://user-images.githubusercontent.com/36684960/48942293-e36c0580-eeec-11e8-9d40-50ce46be6be3.png)

**Comment by daisyzarzo** [comment]
![image](https://user-images.githubusercontent.com/36684960/48945320-df91b080-eef7-11e8-8a4d-cec6cb96ef71.png)

**Comment by MKen-li** [comment]
Marked as verified
Build dev-205
