### ISSUE TITLE
Cancel my subscription

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#965]
### Summary
As a user of the Dashboard
I would like to be able to cancel my subscription

### Acceptance Criteria

1. GIVEN: I'm a user of Dashboard.
WHEN: I go into "My account"
THEN: I see the following:
- User Details Section
    - Change Password has been moved under Email (left aligned)
    - Remove my account has been moved at the bottom (left aligned)
- Subscription Section
    - More info link has been changed for an info icon (link should be the same as before)
    - Want to change your plan? line has been removed
    - An "Unsubscribe" link at the bottom.

2. GIVEN: I'm on "My account"
WHEN: I click on "Unsubscribe"
THEN: A confirmation modal appears
- Title: Unsubscribe
- Text: Are you sure you want to unsubscribe? If you do, you will lose access to the Dashboard and your Virtual Devices on *__next billing date__*
- Buttons: Ok, Cancel

3. GIVEN: I'm on the Unsubscribe modal
WHEN: I click on Cancel
THEN: The modal closes, nothing happens

4. GIVEN: I'm on the Unsubscribe modal
WHEN: I click on Ok
THEN: 
- The modal closes
- A snackbar appears: Your subscription has been canceled. You will lose access on *__next billing date*__
- The stripe subscription is canceled for the current user
- The user will still have access until the last day of his current subscription
- The Unsubscribe link does not appear anymore
- Instead of the Unsubscribe link I can see the following text in red:
    >Ends on:  *__next billing date__*

5. GIVEN: I'm a user on his trial period
WHEN: I go into my account
THEN: I don't see the unsubscribe button.

### Additional Resources
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/6411740/51401059-e44d9c00-1b17-11e9-9e75-ef0aad306e4a.png">

**Comment by MKen-li** [comment]
Marking ticket as blocked, waiting for bugs resolution

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-254
