### ISSUE TITLE
Code free integration is not working correctly

### ISSUE THREAD

**Issue by jperata** [bespoken/dashboard#967]
**Preconditions**

**Steps To Reproduce**
1. Go to the settings tab
2. Click on advance
3. Set up an url for code free integration

**Expected behavior**
Source points to the indicated url

**Actual behavior**
Source points to proxy

**Environment:**
 "version": "1.0.54",

**Additional context**
The sources can be reviewed on dynamo to see how are they being created.

**Comment by dmarvp** [comment]
no longer relevant, since we are removing the settings page.
