### ISSUE TITLE
Configuration section should be not be required for YAML editor

### ISSUE THREAD

**Issue by jkelvie** [bespoken/dashboard#987]
**Preconditions**
Enable the YAML editor

**Steps To Reproduce**
1. Enable the YAML editor

**Expected behavior**
The user can create a script without setting the locale or token in the configuration section of the script.

The locale and token should be automatically taken from the configuration fields in the UI.

**Actual behavior**
The user must set the locale and virtualDeviceToken in the script.

This behavior is negative, because it forces these values to be set twice.

**Comment by dmarvp** [comment]
### Update
After reviewing the issue this is the way I think we should go.

1. GIVEN: I'm a user of the dashboard on the validation page with a virtual device created and a validation script.
WHEN: I turn on the YAML editor toggle.
THEN: I'm taken to the YAML editor page and I see:
    - Dropdowns for virtual device and locale still enabled.
    - My validation script in YAML format.
    - NO configuration section.

2. GIVEN: I'm a user of the Dashboard on the YAML validation page.
WHEN: I click run on a valid YAML script
THEN: 
    - The script is run with configuration created internally and based on the selected virtual device token + locale. 
    - The same behavior should remain when monitoring a YAML script.

#### Additional context.
- Make use of an internal variable that always has the YAML script updated (including configuration) but not completely visible to the user.
- If the users enter another configuration section by typing, we won't control that scenario.

**Comment by jkelvie** [comment]
We should set the locale and virtualDeviceToken using the global configuration. In that way, someone within a script in the YAML editor can add a configuration element and it will override the global configuration.

The global configuration is set on the TestRunner:
https://github.com/bespoken/skill-testing-ml/blob/master/lib/runner/TestRunner.js#L11

It follows the format of the testing.json file:
https://read.bespoken.io/end-to-end/guide/#configuration

The locale and virtualDeviceToken can be set here.

**Comment by MKen-li** [comment]
Marked as blocked, waiting for bug fixes

**Comment by MKen-li** [comment]
Marked as verified.
Build = dev-262
