### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by dmarvp** [bespoken/dashboard#996]
### Summary

As a user of the Dashboard
I want to be able to login with Google

### Acceptance Criteria

1. GIVEN: I'm a user of the Dashboard
WHEN: I'm on the Login Page
THEN: I see a new Login with Google button under the Login with Amazon one.
We can go with the light version from here: https://developers.google.com/identity/branding-guidelines

2. GIVEN: I'm a user on the Login page.
WHEN: I click on the Log in with Google button.
THEN: I see the Google authentication modal.

3. GIVEN: I'm a user on the Login page, the Google authentication modal is open.
WHEN: I close or click on cancel.
THEN: I'm not logged in. Nothing changes.

3. GIVEN: I'm a user on the Login page, the Google authentication modal is open.
WHEN: I enter valid Google credentials.
THEN: I'm logged in into the Dashboard. If this is the first time, a new user record is created with provider = Google.

https://firebase.google.com/docs/auth/?gclid=Cj0KCQiArenfBRCoARIsAFc1Fqf4D48W5WyfbZqz4ynqUMt4kBAdRb3fEhBtS2POSxnfwPhV3VJk3OAaAvpQEALw_wcB

**Comment by MKen-li** [comment]
Marked as verified
Build = dev-216
